import { User } from '@/types';

const photo = (seed: string, w = 400, h = 500) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const MOCK_USERS: User[] = [
  {
    id: 'mock-1',
    email: 'amara@example.com',
    username: 'amara_g',
    full_name: 'Amara Gueye',
    avatar_url: photo('amara', 400, 500),
    profile_photos: [photo('amara', 400, 500), photo('amara2', 400, 500)],
    birthdate: '1996-03-14',
    age: 29,
    gender: 'female',
    interested_in: 'men',
    looking_for: ['relationship', 'marriage'],
    country: 'Senegal',
    state: 'Dakar',
    city: 'Dakar',
    bio: 'Architect by day, home cook by night. I love exploring markets and trying new recipes. Looking for someone who values family and adventure in equal measure.',
    religion: 'islam',
    education: 'masters',
    marital_status: 'single',
    height_cm: 168,
    ethnicity: 'Wolof',
    occupation: 'Architect',
    languages: ['French', 'Wolof', 'English'],
    has_children: false,
    want_children: 'yes',
    online_status: 'online',
    last_seen: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    email: 'kofi@example.com',
    username: 'kofi_b',
    full_name: 'Kofi Boateng',
    avatar_url: photo('kofi'),
    profile_photos: [photo('kofi'), photo('kofi3')],
    birthdate: '1993-07-22',
    age: 31,
    gender: 'male',
    interested_in: 'women',
    looking_for: ['relationship'],
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    bio: 'Software engineer in London, Ghanaian at heart. I visit home every Christmas. Big football fan — AFCON is like Christmas to me.',
    religion: 'christianity',
    education: 'bachelors',
    marital_status: 'single',
    height_cm: 181,
    ethnicity: 'Akan',
    occupation: 'Software Engineer',
    languages: ['English', 'Twi'],
    has_children: false,
    want_children: 'open',
    online_status: 'online',
    last_seen: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    email: 'fatima@example.com',
    username: 'fatima_d',
    full_name: 'Fatima Diallo',
    avatar_url: photo('fatima'),
    profile_photos: [photo('fatima'), photo('fatima2')],
    birthdate: '1998-11-05',
    age: 26,
    gender: 'female',
    interested_in: 'men',
    looking_for: ['friendship', 'relationship'],
    country: 'Nigeria',
    state: 'Lagos',
    city: 'Lagos',
    bio: 'Doctor in training. Love Afrobeats, jollof debates, and long walks on the beach. Fluent in 3 languages.',
    religion: 'islam',
    education: 'masters',
    marital_status: 'single',
    height_cm: 163,
    ethnicity: 'Fulani',
    occupation: 'Medical Doctor (Resident)',
    languages: ['English', 'Hausa', 'French'],
    has_children: false,
    want_children: 'yes',
    online_status: 'offline',
    last_seen: new Date(Date.now() - 30 * 60000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    email: 'emeka@example.com',
    username: 'emeka_o',
    full_name: 'Emeka Okonkwo',
    avatar_url: photo('emeka'),
    profile_photos: [photo('emeka')],
    birthdate: '1990-02-19',
    age: 35,
    gender: 'male',
    interested_in: 'women',
    looking_for: ['marriage'],
    country: 'Nigeria',
    state: 'Anambra',
    city: 'Awka',
    bio: 'Entrepreneur running a logistics company. Family-oriented, God-fearing, and love to laugh. Looking for a serious partner to build with.',
    religion: 'pentecostal',
    education: 'bachelors',
    marital_status: 'single',
    height_cm: 177,
    ethnicity: 'Igbo',
    occupation: 'Entrepreneur',
    languages: ['English', 'Igbo'],
    has_children: false,
    want_children: 'yes',
    online_status: 'offline',
    last_seen: new Date(Date.now() - 2 * 3600000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-5',
    email: 'aisha@example.com',
    username: 'aisha_m',
    full_name: 'Aisha Mensah',
    avatar_url: photo('aisha'),
    profile_photos: [photo('aisha'), photo('aisha2'), photo('aisha3')],
    birthdate: '1995-09-30',
    age: 29,
    gender: 'female',
    interested_in: 'men',
    looking_for: ['relationship', 'friendship'],
    country: 'Kenya',
    state: 'Nairobi',
    city: 'Nairobi',
    bio: 'Marketing director at a tech startup. Obsessed with travel — 18 countries and counting. Half Kenyan, half Ghanaian, raised in the UK.',
    religion: 'christianity',
    education: 'masters',
    marital_status: 'single',
    height_cm: 170,
    ethnicity: 'Kikuyu / Akan',
    occupation: 'Marketing Director',
    languages: ['English', 'Swahili', 'Twi'],
    has_children: false,
    want_children: 'open',
    online_status: 'online',
    last_seen: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-6',
    email: 'ibrahim@example.com',
    username: 'ibrahim_t',
    full_name: 'Ibrahim Touré',
    avatar_url: photo('ibrahim'),
    profile_photos: [photo('ibrahim'), photo('ibrahim2')],
    birthdate: '1991-06-12',
    age: 34,
    gender: 'male',
    interested_in: 'women',
    looking_for: ['relationship', 'marriage'],
    country: "Côte d'Ivoire",
    state: 'Abidjan',
    city: 'Abidjan',
    bio: 'Civil engineer. Music producer on weekends. Born in Abidjan, now in Paris. Looking to connect with someone who values both cultures.',
    religion: 'islam',
    education: 'masters',
    marital_status: 'single',
    height_cm: 184,
    ethnicity: 'Mandé',
    occupation: 'Civil Engineer',
    languages: ['French', 'Dioula', 'English'],
    has_children: false,
    want_children: 'yes',
    online_status: 'online',
    last_seen: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-7',
    email: 'grace@example.com',
    username: 'grace_n',
    full_name: 'Grace Ndegwa',
    avatar_url: photo('grace'),
    profile_photos: [photo('grace')],
    birthdate: '1997-01-25',
    age: 28,
    gender: 'female',
    interested_in: 'men',
    looking_for: ['relationship'],
    country: 'Kenya',
    state: 'Mombasa',
    city: 'Mombasa',
    bio: 'Nurse and part-time yoga instructor. Beach lover, sunrise chaser. Believe in kindness first.',
    religion: 'christianity',
    education: 'bachelors',
    marital_status: 'single',
    height_cm: 165,
    ethnicity: 'Kikuyu',
    occupation: 'Registered Nurse',
    languages: ['English', 'Swahili'],
    has_children: false,
    want_children: 'yes',
    online_status: 'offline',
    last_seen: new Date(Date.now() - 15 * 60000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-8',
    email: 'seun@example.com',
    username: 'seun_a',
    full_name: 'Seun Adeyemi',
    avatar_url: photo('seun'),
    profile_photos: [photo('seun'), photo('seun2')],
    birthdate: '1994-04-08',
    age: 31,
    gender: 'male',
    interested_in: 'women',
    looking_for: ['relationship', 'pen_pal'],
    country: 'United States',
    state: 'Texas',
    city: 'Houston',
    bio: 'Nigerian-American lawyer in Houston. Love cooking Nigerian food, hiking, and jazz. Searching for my missing rib 😄',
    religion: 'pentecostal',
    education: 'phd',
    marital_status: 'single',
    height_cm: 179,
    ethnicity: 'Yoruba',
    occupation: 'Attorney',
    languages: ['English', 'Yoruba'],
    has_children: false,
    want_children: 'yes',
    online_status: 'offline',
    last_seen: new Date(Date.now() - 5 * 3600000).toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-9',
    email: 'zara@example.com',
    username: 'zara_a',
    full_name: 'Zara Ahmed',
    avatar_url: photo('zara'),
    profile_photos: [photo('zara'), photo('zara2')],
    birthdate: '1999-08-17',
    age: 25,
    gender: 'female',
    interested_in: 'men',
    looking_for: ['marriage'],
    country: 'Ethiopia',
    state: 'Addis Ababa',
    city: 'Addis Ababa',
    bio: 'Fashion designer with a studio in Addis. Inspired by African textiles and global trends. Dreaming of building something meaningful with the right person.',
    religion: 'islam',
    education: 'bachelors',
    marital_status: 'single',
    height_cm: 162,
    ethnicity: 'Amhara',
    occupation: 'Fashion Designer',
    languages: ['Amharic', 'English', 'Arabic'],
    has_children: false,
    want_children: 'yes',
    online_status: 'online',
    last_seen: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-10',
    email: 'david@example.com',
    username: 'david_m',
    full_name: 'David Mwangi',
    avatar_url: photo('david'),
    profile_photos: [photo('david'), photo('david2')],
    birthdate: '1988-12-03',
    age: 36,
    gender: 'male',
    interested_in: 'women',
    looking_for: ['relationship', 'marriage'],
    country: 'Canada',
    state: 'Ontario',
    city: 'Toronto',
    bio: 'Kenyan-Canadian architect. Passionate about sustainable design and African urbanism. Weekend chef, amateur photographer.',
    religion: 'orthodox_christian',
    education: 'masters',
    marital_status: 'divorced',
    height_cm: 183,
    ethnicity: 'Kikuyu',
    occupation: 'Architect',
    languages: ['English', 'Swahili'],
    has_children: true,
    want_children: 'open',
    online_status: 'online',
    last_seen: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
