import { StyleSheet } from 'react-native';
import { COLORS, RADIUS, FONT, SHADOWS } from '@/constants';

export const chatScreenStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    gap: 8,
  },
  backBtn: { padding: 4 },
  headerAvatar: { width: 38, height: 38, borderRadius: 19 },
  onlineDot: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  headerName: { fontSize: 16, fontWeight: FONT.bold, color: COLORS.textStrong, letterSpacing: 0.1 },
  headerStatus: { fontSize: FONT.xs, fontWeight: FONT.semibold, marginTop: 2, letterSpacing: 0.2 },
  iconBtn: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  backdrop: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 1001 },
  dropdown: {
    position: 'absolute',
    right: 12,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingVertical: 6,
    minWidth: 180,
    ...SHADOWS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    zIndex: 1002,
  },
  menuItem: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 12, gap: 12 },
  menuIcon: {
    width: 32,
    height: 32,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.savanna,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuLabel: { fontSize: FONT.md, fontWeight: FONT.semibold, color: COLORS.textStrong },
  datePill: {
    fontSize: 11,
    fontWeight: FONT.semibold,
    color: COLORS.textSecondary,
    backgroundColor: COLORS.savanna,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: RADIUS.full,
    letterSpacing: 0.3,
    overflow: 'hidden',
  },
  disabledBar: {
    padding: 16,
    backgroundColor: COLORS.white,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
    alignItems: 'center',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: COLORS.white,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
    gap: 8,
  },
  input: {
    flex: 1,
    minHeight: 42,
    maxHeight: 120,
    backgroundColor: COLORS.savanna,
    borderRadius: RADIUS.full,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: FONT.md,
    color: COLORS.textStrong,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'transparent',
  },
  inputFocused: { borderColor: COLORS.primaryBorder, backgroundColor: COLORS.white },
  sendBtn: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  ctxBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.overlayLight,
    zIndex: 998,
  },
  reactionBtn: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center' },
  reactionBtnActive: {
    backgroundColor: COLORS.primarySurface,
    borderWidth: 1,
    borderColor: COLORS.primaryBorder,
  },
  reactionCard: {
    position: 'absolute',
    left: 24,
    right: 24,
    top: '22%',
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xxl,
    overflow: 'hidden',
    zIndex: 999,
    ...SHADOWS.lg,
  },
});
