import { StyleSheet } from 'react-native';
import { COLORS, FONT, RADIUS, SHADOWS } from '@/constants';

/** Styles for `app/(profile)/[id].tsx` — split out to shrink the screen file. */
export const pr = StyleSheet.create({
  identityCard: {
    marginTop: 0,
    marginHorizontal: 16,
    marginBottom: 4,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.xl,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    ...SHADOWS.md,
  },
  identityHeaderBlock: {
    gap: 6,
  },
  identityTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  identityNameWrap: {
    flex: 1,
    minWidth: 140,
  },
  displayName: {
    fontSize: FONT.xxl,
    fontWeight: FONT.extrabold,
    color: COLORS.textStrong,
    lineHeight: 32,
    letterSpacing: 0.1,
  },
  displayAge: {
    fontSize: FONT.xl,
    fontWeight: FONT.medium,
    color: COLORS.textSecondary,
  },
  verifiedInlineIcon: {
    marginTop: 2,
  },
  identitySubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  identityLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexShrink: 1,
    minWidth: 0,
  },
  identityLocationText: {
    flexShrink: 1,
    fontSize: FONT.sm,
    color: COLORS.textSecondary,
    fontWeight: FONT.semibold,
  },
  identityStatusInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 0,
  },
  chipHobby: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.savanna,
    borderWidth: 1,
    borderColor: `${COLORS.earth}35`,
  },
  chipHobbyText: { fontSize: FONT.sm, color: COLORS.earth, fontWeight: FONT.semibold },
  frostedCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(0,0,0,0.18)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  collapsedHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    backgroundColor: COLORS.white,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
    ...SHADOWS.sm,
  },
  collapsedHeaderInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    minHeight: 56,
  },
  collapsedBackBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collapsedAvatarWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'visible',
    marginLeft: 2,
  },
  collapsedAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.savanna,
  },
  collapsedOnlineDot: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: COLORS.online,
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  collapsedName: {
    fontSize: 15,
    fontWeight: FONT.extrabold,
    color: COLORS.textStrong,
    letterSpacing: 0.1,
  },
  collapsedAge: {
    fontWeight: FONT.bold,
    color: COLORS.textSecondary,
  },
  collapsedStatus: {
    fontSize: 12,
    fontWeight: FONT.semibold,
    marginTop: 1,
  },
  collapsedMenuBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sharedBlock: {
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
  },
  sharedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  sharedHeaderText: {
    fontSize: 11,
    fontWeight: FONT.extrabold,
    color: COLORS.primary,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  sharedChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  sharedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.full,
    backgroundColor: `${COLORS.primary}12`,
    borderWidth: 1,
    borderColor: `${COLORS.primary}30`,
  },
  sharedChipLang: {
    backgroundColor: COLORS.savanna,
    borderColor: `${COLORS.earth}30`,
  },
  sharedChipText: {
    fontSize: 12,
    color: COLORS.earth,
    fontWeight: FONT.semibold,
  },
  aboutBlock: { flexDirection: 'row', marginTop: 18, alignItems: 'flex-start' },
  aboutAccent: {
    width: 4,
    marginTop: 4,
    minHeight: 52,
    borderRadius: 2,
    backgroundColor: COLORS.textStrong,
    marginRight: 14,
  },
  aboutLabel: {
    fontSize: FONT.sm,
    fontWeight: FONT.extrabold,
    color: COLORS.textStrong,
    marginBottom: 8,
  },
  aboutBody: {
    fontSize: FONT.md,
    color: COLORS.text,
    lineHeight: 24,
    fontWeight: FONT.medium,
  },
  sectionCard: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
    ...SHADOWS.sm,
  },
  heroDotsRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 7,
  },
  heroDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,0.48)',
  },
  heroDotActive: {
    width: 22,
    backgroundColor: '#FFF',
  },
  quickFactsBlock: {
    marginTop: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
    paddingTop: 4,
  },
  detailsToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 12,
    paddingVertical: 14,
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.full,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.border,
    ...SHADOWS.sm,
  },
  detailsToggleLabel: {
    fontSize: FONT.md,
    fontWeight: FONT.extrabold,
    color: COLORS.textStrong,
    letterSpacing: 0.2,
  },
  upNextFooter: {
    paddingTop: 28,
    paddingBottom: 56,
    alignItems: 'center',
    gap: 10,
  },
  upNextHandle: {
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: COLORS.borderStrong,
  },
  quickFactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
  },
  quickFactRowDivider: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  quickFactIcon: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.savanna,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickFactLabel: {
    fontSize: 11,
    fontWeight: FONT.extrabold,
    color: COLORS.textMuted,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  quickFactValue: {
    fontSize: FONT.md,
    fontWeight: FONT.semibold,
    color: COLORS.textStrong,
    lineHeight: 20,
  },
  sectionTitle: {
    fontSize: FONT.xs,
    fontWeight: FONT.extrabold,
    color: COLORS.earth,
    letterSpacing: 1,
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  onlineBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  onlineBadgeText: {
    fontSize: 11,
    fontWeight: FONT.regular,
    letterSpacing: 0.1,
  },
  messagePausedNote: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: RADIUS.full,
    backgroundColor: 'rgba(255,255,255,0.94)',
    ...SHADOWS.sm,
  },
  messagePausedNoteText: {
    fontSize: 12,
    color: COLORS.textSecondary,
    fontWeight: FONT.medium,
  },
});
