export const COLORS = {
  primary: '#C84B31',
  primaryLight: '#E07F66',
  primaryDark: '#A33B26',
  earth: '#8B5E3C',
  earthLight: '#D4A574',
  savanna: '#F5E6D0',
  gold: '#D4AF37',
  green: '#2D6A4F',
  surface: '#FAFAF8',
  card: '#FFFFFF',
  text: '#1A1A1A',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  border: '#E5E7EB',
  error: '#EF4444',
  success: '#10B981',
  warning: '#F59E0B',
  online: '#10B981',
  offline: '#9CA3AF',
} as const;

export const AFRICAN_COUNTRIES = [
  { code: 'DZ', name: 'Algeria' },
  { code: 'AO', name: 'Angola' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cape Verde' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'DR Congo' },
  { code: 'CI', name: 'Côte d\'Ivoire' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'EG', name: 'Egypt' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'SZ', name: 'Eswatini' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'KE', name: 'Kenya' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'ML', name: 'Mali' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'ST', name: 'São Tomé and Príncipe' },
  { code: 'SN', name: 'Senegal' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'SD', name: 'Sudan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TG', name: 'Togo' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'UG', name: 'Uganda' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
  // Diaspora countries
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'CA', name: 'Canada' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'AU', name: 'Australia' },
  { code: 'SE', name: 'Sweden' },
  { code: 'NO', name: 'Norway' },
  { code: 'IT', name: 'Italy' },
  { code: 'ES', name: 'Spain' },
  { code: 'BE', name: 'Belgium' },
  { code: 'PT', name: 'Portugal' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'QA', name: 'Qatar' },
  { code: 'NZ', name: 'New Zealand' },
];

export const GENDER_OPTIONS = [
  { value: 'male',   label: 'Man' },
  { value: 'female', label: 'Woman' },
];

export const LOOKING_FOR_OPTIONS = [
  { value: 'relationship', label: 'Relationship' },
  { value: 'marriage', label: 'Marriage' },
  { value: 'friendship', label: 'Friendship' },
  { value: 'pen_pal', label: 'Pen Pal' },
];

export const RELIGION_OPTIONS = [
  { value: 'christianity',       label: 'Christianity',        emoji: '✝️' },
  { value: 'catholicism',        label: 'Catholic',            emoji: '✝️' },
  { value: 'protestantism',      label: 'Protestant',          emoji: '✝️' },
  { value: 'pentecostal',        label: 'Pentecostal',         emoji: '✝️' },
  { value: 'orthodox_christian', label: 'Orthodox Christian',  emoji: '☦️' },
  { value: 'islam',              label: 'Islam',               emoji: '☪️' },
  { value: 'traditional_african',label: 'Traditional African', emoji: '🌿' },
  { value: 'judaism',            label: 'Judaism',             emoji: '✡️' },
  { value: 'buddhism',           label: 'Buddhism',            emoji: '☸️' },
  { value: 'hinduism',           label: 'Hinduism',            emoji: '🕉️' },
  { value: 'atheist',            label: 'Atheist',             emoji: '⚛️' },
  { value: 'agnostic',           label: 'Agnostic',            emoji: '🤔' },
  { value: 'spiritual',          label: 'Spiritual',           emoji: '🌟' },
  { value: 'other',              label: 'Other',               emoji: '🙏' },
];

export const EDUCATION_OPTIONS = [
  { value: 'high_school',    label: 'High School' },
  { value: 'some_college',   label: 'Some College' },
  { value: 'vocational',     label: 'Vocational / Trade' },
  { value: 'bachelors',      label: "Bachelor's Degree" },
  { value: 'masters',        label: "Master's Degree" },
  { value: 'phd',            label: 'PhD / Doctorate' },
  { value: 'other',          label: 'Other' },
];

export const OCCUPATION_OPTIONS = [
  { value: 'accountant', label: 'Accountant' },
  { value: 'administrator', label: 'Administrator' },
  { value: 'architect', label: 'Architect' },
  { value: 'artist', label: 'Artist' },
  { value: 'banker', label: 'Banker' },
  { value: 'business_owner', label: 'Business Owner' },
  { value: 'chef', label: 'Chef' },
  { value: 'civil_servant', label: 'Civil Servant' },
  { value: 'consultant', label: 'Consultant' },
  { value: 'customer_service', label: 'Customer Service' },
  { value: 'designer', label: 'Designer' },
  { value: 'developer', label: 'Developer / Engineer' },
  { value: 'doctor', label: 'Doctor / Physician' },
  { value: 'driver', label: 'Driver' },
  { value: 'electrician', label: 'Electrician' },
  { value: 'engineer', label: 'Engineer' },
  { value: 'entrepreneur', label: 'Entrepreneur' },
  { value: 'farmer', label: 'Farmer' },
  { value: 'financial_analyst', label: 'Financial Analyst' },
  { value: 'government_worker', label: 'Government Worker' },
  { value: 'hair_beauty', label: 'Hair / Beauty Professional' },
  { value: 'healthcare_worker', label: 'Healthcare Worker' },
  { value: 'hospitality', label: 'Hospitality' },
  { value: 'hr', label: 'Human Resources' },
  { value: 'journalist', label: 'Journalist / Media' },
  { value: 'lawyer', label: 'Lawyer' },
  { value: 'lecturer', label: 'Lecturer / Professor' },
  { value: 'manager', label: 'Manager' },
  { value: 'marketing', label: 'Marketing / Sales' },
  { value: 'mechanic', label: 'Mechanic' },
  { value: 'military', label: 'Military / Security' },
  { value: 'musician', label: 'Musician / Entertainer' },
  { value: 'nurse', label: 'Nurse' },
  { value: 'pharmacist', label: 'Pharmacist' },
  { value: 'photographer', label: 'Photographer' },
  { value: 'pilot', label: 'Pilot / Aviation' },
  { value: 'police', label: 'Police / Law Enforcement' },
  { value: 'project_manager', label: 'Project Manager' },
  { value: 'real_estate', label: 'Real Estate' },
  { value: 'researcher', label: 'Researcher' },
  { value: 'retail', label: 'Retail / Trade' },
  { value: 'student', label: 'Student' },
  { value: 'teacher', label: 'Teacher' },
  { value: 'technician', label: 'Technician' },
  { value: 'trader', label: 'Trader / Merchant' },
  { value: 'writer', label: 'Writer' },
  { value: 'other', label: 'Other' },
] as const;

export const PHYSICAL_CONDITION_OPTIONS = [
  { value: 'slim', label: 'Slim' },
  { value: 'athletic', label: 'Athletic' },
  { value: 'average', label: 'Average' },
  { value: 'curvy', label: 'Curvy' },
  { value: 'plus_size', label: 'Plus Size' },
  { value: 'prefer_not_to_say', label: 'Prefer not to say' },
] as const;

export const MARITAL_STATUS_OPTIONS = [
  { value: 'single',    label: 'Single',    emoji: '🙂' },
  { value: 'divorced',  label: 'Divorced',  emoji: '💔' },
  { value: 'widowed',   label: 'Widowed',   emoji: '🕊️' },
  { value: 'separated', label: 'Separated', emoji: '↔️' },
];

export const WANT_CHILDREN_OPTIONS = [
  { value: 'yes',  label: 'Yes, I want kids' },
  { value: 'no',   label: "No, I don't" },
  { value: 'open', label: 'Open to it' },
];

export const APP_NAME = 'Africana';
export const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL ?? '';
export const SUPABASE_ANON_KEY = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? '';

export const DEFAULT_AVATAR = 'https://ui-avatars.com/api/?background=C84B31&color=fff&size=200&name=';
export const MAX_PROFILE_PHOTOS = 6;
export const MIN_AGE = 18;
export const MAX_AGE = 100;
