import { CountryCultureData } from './types';

export const CENTRAL_AFRICA_CULTURE: Record<string, CountryCultureData> = {
  CD: {
    ethnicities: [
      'Luba',
      'Mongo',
      'Kongo',
      'Lingala',
      'Hunde',
      'Nande',
      'Tetela',
      'Lulua',
      'Bashi',
      'Lega',
      'Hemba',
      'Lunda',
      'Chokwe',
      'Azande',
      'Mangbetu',
      'Songye',
      'Yaka',
      'Pende',
      'Ngombe',
      'Kuba',
      'Tutsi',
      'Hutu',
      'Pygmy',
      'Mixed / Other',
    ],
    languages: [
      'French',
      'Swahili',
      'Lingala',
      'Tshiluba',
      'Kikongo',
      'Luba-Katanga',
      'Kikongo ya Leta',
    ],
    subdivisionEthnicities: {
      Kinshasa: ['Lingala', 'Kongo', 'Luba', 'Mongo', 'Mixed / Other'],
      'Kongo Central': ['Kongo', 'Yombe'],
      Kwango: ['Yaka', 'Pende', 'Suku'],
      Kwilu: ['Pende', 'Mbala', 'Yaka'],
      'Mai-Ndombe': ['Mongo', 'Ekonda', 'Ntomba'],
      Kasaï: ['Luba', 'Lulua'],
      'Kasaï-Central': ['Luba', 'Lulua'],
      'Kasaï-Oriental': ['Luba', 'Songye'],
      Lomami: ['Luba', 'Songye', 'Kanyok'],
      Sankuru: ['Tetela', 'Kuba', 'Luba'],
      Maniema: ['Lega', 'Songye', 'Tetela'],
      'Sud-Kivu': ['Bashi', 'Lega', 'Hutu', 'Tutsi'],
      'Nord-Kivu': ['Nande', 'Hunde', 'Hutu', 'Tutsi'],
      Ituri: ['Hema', 'Lendu', 'Pygmy', 'Nande'],
      'Haut-Uele': ['Azande', 'Mangbetu'],
      'Bas-Uele': ['Azande', 'Boa', 'Mangbetu'],
      Tshopo: ['Mongo', 'Lokele', 'Topoke'],
      Mongala: ['Mongo', 'Ngombe'],
      'Nord-Ubangi': ['Ngbaka', 'Mbanza', 'Mono'],
      'Sud-Ubangi': ['Ngombe', 'Ngbaka'],
      Équateur: ['Mongo', 'Ngombe'],
      Tshuapa: ['Mongo', 'Tetela'],
      Tanganyika: ['Luba', 'Hemba', 'Tabwa'],
      'Haut-Lomami': ['Luba', 'Hemba', 'Lunda'],
      Lualaba: ['Lunda', 'Chokwe', 'Ndembo'],
      'Haut-Katanga': ['Luba-Katanga', 'Hemba', 'Bemba', 'Lunda'],
    },
    cityEthnicities: {
      Kinshasa: ['Lingala', 'Kongo', 'Luba', 'Mongo', 'Mixed / Other'],
      Lubumbashi: ['Luba-Katanga', 'Bemba', 'Hemba'],
      'Mbuji-Mayi': ['Luba'],
      Kisangani: ['Mongo', 'Lokele', 'Tetela'],
      Bukavu: ['Bashi', 'Lega', 'Hutu', 'Tutsi'],
      Goma: ['Nande', 'Hunde', 'Hutu', 'Tutsi'],
      Kananga: ['Luba', 'Lulua'],
      Matadi: ['Kongo'],
      Mbandaka: ['Mongo'],
      Kindu: ['Lega', 'Songye'],
      Bunia: ['Hema', 'Lendu', 'Nande'],
      Kolwezi: ['Lunda', 'Chokwe', 'Ndembo'],
      Likasi: ['Luba-Katanga', 'Hemba'],
      Tshikapa: ['Luba', 'Chokwe'],
      Kikwit: ['Pende', 'Yaka'],
      Butembo: ['Nande'],
      Isiro: ['Azande', 'Mangbetu'],
    },
    ethnicityLanguages: {
      Luba: ['Tshiluba', 'Luba-Katanga', 'French'],
      Mongo: ['Lingala', 'French'],
      Kongo: ['Kikongo', 'Lingala', 'French'],
      Lingala: ['Lingala', 'French'],
      Hunde: ['Swahili', 'French'],
      Nande: ['Swahili', 'French'],
      Tetela: ['Lingala', 'French'],
      Lulua: ['Tshiluba', 'Lingala', 'French'],
      Bashi: ['Mashi', 'Swahili', 'French'],
      Lega: ['Lega', 'Swahili', 'French'],
      Hemba: ['Hemba', 'Swahili', 'French'],
      Lunda: ['Lunda', 'French'],
      Chokwe: ['Chokwe', 'French'],
      Azande: ['Zande', 'Lingala', 'French'],
      Mangbetu: ['Mangbetu', 'Lingala', 'French'],
      Songye: ['Songye', 'Tshiluba', 'French'],
      Yaka: ['Yaka', 'French'],
      Pende: ['Pende', 'French'],
      Ngombe: ['Ngombe', 'Lingala', 'French'],
      Kuba: ['Kuba', 'Tshiluba', 'French'],
      Tutsi: ['Kinyarwanda', 'Swahili', 'French'],
      Hutu: ['Kinyarwanda', 'Swahili', 'French'],
      Pygmy: ['Lingala', 'French'],
      'Mixed / Other': ['French', 'Lingala'],
    },
    subdivisionLanguages: {
      Kinshasa: ['Lingala', 'French'],
      'Kongo Central': ['Kikongo', 'French'],
      Kasaï: ['Tshiluba', 'French'],
      'Kasaï-Central': ['Tshiluba', 'French'],
      'Kasaï-Oriental': ['Tshiluba', 'French'],
      'Nord-Kivu': ['Swahili', 'French'],
      'Sud-Kivu': ['Swahili', 'French'],
      'Haut-Katanga': ['Swahili', 'French'],
      Lualaba: ['Swahili', 'French'],
      Ituri: ['Swahili', 'Lingala', 'French'],
      Équateur: ['Lingala', 'French'],
      Tshopo: ['Lingala', 'Swahili', 'French'],
    },
  },
  CG: {
    ethnicities: [
      'Kongo',
      'Lari',
      'Vili',
      'Teke',
      'Mbochi',
      'Sangha',
      'Bembe',
      'Punu',
      'Kota',
      'Pygmy',
      'Mixed / Other',
    ],
    languages: ['French', 'Lingala', 'Kituba', 'Teke', 'Mboshi'],
    subdivisionEthnicities: {
      Brazzaville: ['Lari', 'Kongo', 'Mbochi', 'Teke'],
      Pointe_Noire: ['Vili', 'Punu', 'Kongo'],
      Kouilou: ['Vili', 'Punu'],
      Niari: ['Bembe', 'Kongo', 'Teke'],
      Lékoumou: ['Teke', 'Bembe'],
      Bouenza: ['Kongo', 'Bembe'],
      Pool: ['Lari', 'Kongo', 'Teke'],
      Plateaux: ['Teke'],
      Cuvette: ['Mbochi', 'Makoua'],
      'Cuvette-Ouest': ['Mbochi', 'Kota'],
      Sangha: ['Sangha', 'Pygmy'],
      Likouala: ['Sangha', 'Pygmy', 'Mbochi'],
    },
    cityEthnicities: {
      Brazzaville: ['Lari', 'Kongo', 'Mbochi', 'Teke'],
      'Pointe-Noire': ['Vili', 'Punu', 'Kongo'],
      Dolisie: ['Kongo', 'Teke', 'Bembe'],
      Owando: ['Mbochi', 'Makoua'],
      Ouesso: ['Sangha', 'Pygmy'],
      'Madingou (Bouenza)': ['Kongo', 'Bembe'],
      Sibiti: ['Teke', 'Bembe'],
      Djambala: ['Teke'],
    },
    ethnicityLanguages: {
      Kongo: ['Kituba', 'Kikongo', 'Lingala', 'French'],
      Lari: ['Lingala', 'French'],
      Vili: ['Kikongo', 'Lingala', 'French'],
      Teke: ['Teke', 'Lingala', 'French'],
      Mbochi: ['Mboshi', 'Lingala', 'French'],
      Sangha: ['Sangha', 'French'],
      Bembe: ['Bembe', 'Lingala', 'French'],
      Punu: ['Punu', 'Lingala', 'French'],
      Kota: ['Kota', 'French'],
      Pygmy: ['Lingala', 'French'],
      'Mixed / Other': ['French', 'Lingala'],
    },
    subdivisionLanguages: {
      Brazzaville: ['Lingala', 'French', 'Kituba'],
      Pointe_Noire: ['Kituba', 'French', 'Lingala'],
      Kouilou: ['Kituba', 'French'],
      Pool: ['Lingala', 'French', 'Kituba'],
      Plateaux: ['Teke', 'French'],
      Cuvette: ['Mboshi', 'Lingala', 'French'],
    },
  },
  CF: {
    ethnicities: [
      'Gbaya',
      'Banda',
      'Mandjia',
      'Sara',
      'Mboum',
      'Ngbaka',
      'Yakoma',
      'Zande',
      'Pygmy (Aka)',
      'Arab-Chadian',
      'Mixed / Other',
    ],
    languages: ['Sango', 'French', 'Gbaya', 'Banda', 'Mandjia', 'Arabic'],
    subdivisionEthnicities: {
      Bangui: ['Yakoma', 'Banda', 'Gbaya', 'Mandjia'],
      'Ombella-M\'Poko': ['Gbaya', 'Banda', 'Mandjia'],
      Lobaye: ['Pygmy (Aka)', 'Gbaya', 'Ngbaka'],
      Kémo: ['Banda', 'Gbaya'],
      'Nana-Mambéré': ['Gbaya', 'Mandjia'],
      'Ouham-Pendé': ['Gbaya', 'Mandjia', 'Mboum'],
      Ouham: ['Gbaya', 'Mandjia', 'Sara'],
      'Nana-Grébizi': ['Banda', 'Sara'],
      'Bamingui-Bangoran': ['Sara', 'Gula'],
      Vakaga: ['Sara', 'Zande', 'Runga'],
      'Haute-Kotto': ['Banda', 'Zande'],
      Mbomou: ['Azande', 'Banda', 'Ngbaka'],
      'Basse-Kotto': ['Banda', 'Ngbaka'],
      'Haut-Mbomou': ['Zande', 'Banda'],
      'Mambéré-Kadéï': ['Gbaya', 'Mandjia'],
      'Sangha-Mbaéré': ['Pygmy (Aka)', 'Gbaya', 'Sangha'],
    },
    cityEthnicities: {
      Bangui: ['Yakoma', 'Banda', 'Gbaya', 'Mandjia'],
      Bimbo: ['Gbaya', 'Banda', 'Yakoma'],
      Berbérati: ['Gbaya', 'Mandjia'],
      Bambari: ['Banda'],
      Bossangoa: ['Mandjia', 'Gbaya'],
      Bouar: ['Gbaya'],
      'Kaga-Bandoro': ['Banda', 'Mandjia'],
      Mbaïki: ['Pygmy (Aka)', 'Ngbaka'],
      Bria: ['Banda', 'Zande'],
      Bangassou: ['Azande', 'Ngbaka'],
      Birao: ['Sara', 'Runga'],
      Carnot: ['Gbaya'],
    },
    ethnicityLanguages: {
      Gbaya: ['Gbaya', 'Sango', 'French'],
      Banda: ['Banda', 'Sango', 'French'],
      Mandjia: ['Mandjia', 'Sango', 'French'],
      Sara: ['Sara', 'Sango', 'French'],
      Mboum: ['Mboum', 'Sango', 'French'],
      Ngbaka: ['Ngbaka', 'Sango', 'French'],
      Yakoma: ['Yakoma', 'Sango', 'French'],
      Zande: ['Zande', 'Sango', 'French'],
      'Pygmy (Aka)': ['Aka', 'Sango', 'French'],
      'Arab-Chadian': ['Arabic', 'Sango', 'French'],
      'Mixed / Other': ['French', 'Sango'],
    },
    subdivisionLanguages: {
      Bangui: ['Sango', 'French'],
      Lobaye: ['Sango', 'French', 'Aka'],
      'Nana-Mambéré': ['Sango', 'French', 'Gbaya'],
      Vakaga: ['Sango', 'French', 'Arabic'],
      'Haut-Mbomou': ['Sango', 'French', 'Zande'],
    },
  },
  TD: {
    ethnicities: [
      'Sara',
      'Arab',
      'Kanembu',
      'Hadjarai',
      'Toubou',
      'Zaghawa',
      'Gorane',
      'Maba',
      'Moundang',
      'Ouaddaï',
      'Buduma',
      'Massalit',
      'Fulani',
      'Mixed / Other',
    ],
    languages: ['Arabic', 'French', 'Sara', 'Gorane', 'Zaghawa', 'Kanembu'],
    subdivisionEthnicities: {
      'N\'Djamena': ['Arab', 'Sara', 'Kanembu', 'Ouaddaï', 'Mixed / Other'],
      'Bahr el Gazel': ['Kanembu'],
      Batha: ['Arab', 'Ouaddaï', 'Maba'],
      Borkou: ['Toubou', 'Gorane'],
      'Chari-Baguirmi': ['Sara', 'Arab'],
      'Ennedi-Est': ['Toubou', 'Zaghawa'],
      'Ennedi-Ouest': ['Toubou', 'Gorane'],
      Guéra: ['Hadjarai', 'Arab'],
      'Hadjer-Lamis': ['Arab', 'Kanembu'],
      Kanem: ['Kanembu', 'Arab'],
      Lac: ['Kanembu', 'Buduma'],
      'Logone Occidental': ['Sara'],
      'Logone Oriental': ['Sara', 'Moundang'],
      Mandoul: ['Sara'],
      'Mayo-Kebbi Est': ['Sara', 'Moundang'],
      'Mayo-Kebbi Ouest': ['Moundang', 'Fulani'],
      'Moyen-Chari': ['Sara'],
      Ouaddaï: ['Maba', 'Ouaddaï', 'Arab'],
      Salamat: ['Arab', 'Sara'],
      Sila: ['Ouaddaï', 'Arab'],
      Tandjilé: ['Hadjarai', 'Sara'],
      Tibesti: ['Toubou', 'Gorane'],
      'Wadi Fira': ['Zaghawa', 'Maba', 'Massalit'],
    },
    cityEthnicities: {
      'N\'Djamena': ['Arab', 'Sara', 'Kanembu', 'Ouaddaï', 'Mixed / Other'],
      Moundou: ['Sara', 'Moundang'],
      Sarh: ['Sara'],
      Abéché: ['Arab', 'Maba', 'Ouaddaï'],
      Mongo: ['Hadjarai'],
      Bol: ['Kanembu'],
      Faya: ['Toubou', 'Gorane'],
      Am_Timan: ['Arab', 'Sara'],
      Mao: ['Kanembu', 'Arab'],
      Koumra: ['Sara'],
      Biltine: ['Zaghawa', 'Maba'],
      Lai: ['Hadjarai', 'Sara'],
      Pala: ['Moundang', 'Fulani'],
    },
    ethnicityLanguages: {
      Sara: ['Sara', 'Arabic', 'French'],
      Arab: ['Arabic', 'French'],
      Kanembu: ['Kanembu', 'Arabic', 'French'],
      Hadjarai: ['Arabic', 'French'],
      Toubou: ['Toubou', 'Arabic', 'French'],
      Zaghawa: ['Zaghawa', 'Arabic', 'French'],
      Gorane: ['Gorane', 'Arabic', 'French'],
      Maba: ['Maba', 'Arabic', 'French'],
      Moundang: ['Moundang', 'Arabic', 'French'],
      Ouaddaï: ['Arabic', 'French'],
      Buduma: ['Buduma', 'Kanembu', 'Arabic', 'French'],
      Massalit: ['Massalit', 'Arabic', 'French'],
      Fulani: ['Fulfulde', 'Arabic', 'French'],
      'Mixed / Other': ['French', 'Arabic'],
    },
    subdivisionLanguages: {
      'N\'Djamena': ['Arabic', 'French'],
      Borkou: ['Toubou', 'Gorane', 'Arabic', 'French'],
      Tibesti: ['Toubou', 'Gorane', 'Arabic', 'French'],
      'Ennedi-Est': ['Toubou', 'Zaghawa', 'Arabic', 'French'],
      'Ennedi-Ouest': ['Toubou', 'Gorane', 'Arabic', 'French'],
      'Logone Occidental': ['Sara', 'Arabic', 'French'],
      'Logone Oriental': ['Sara', 'Moundang', 'Arabic', 'French'],
      'Mayo-Kebbi Est': ['Sara', 'Moundang', 'Arabic', 'French'],
      'Wadi Fira': ['Zaghawa', 'Maba', 'Arabic', 'French'],
      Ouaddaï: ['Arabic', 'Maba', 'French'],
      Kanem: ['Kanembu', 'Arabic', 'French'],
      Lac: ['Kanembu', 'Buduma', 'Arabic', 'French'],
    },
  },
  GA: {
    ethnicities: [
      'Fang',
      'Myene',
      'Punu',
      'Nzebi',
      'Obamba',
      'Kota',
      'Teke',
      'Baka (Pygmy)',
      'Galoa',
      'Mixed / Other',
    ],
    languages: ['French', 'Fang', 'Punu', 'Nzebi', 'Myene', 'Kota'],
    subdivisionEthnicities: {
      Estuaire: ['Fang', 'Myene', 'Mixed / Other'],
      'Haut-Ogooué': ['Obamba', 'Nzebi', 'Teke'],
      'Moyen-Ogooué': ['Galoa', 'Fang'],
      Ngounié: ['Punu', 'Nzebi'],
      Nyanga: ['Punu'],
      'Ogooué-Ivindo': ['Kota', 'Fang', 'Baka (Pygmy)'],
      'Ogooué-Lolo': ['Nzebi', 'Obamba'],
      'Ogooué-Maritime': ['Myene', 'Fang'],
      'Woleu-Ntem': ['Fang'],
    },
    cityEthnicities: {
      Libreville: ['Fang', 'Myene', 'Mixed / Other'],
      'Port-Gentil': ['Myene', 'Fang'],
      Franceville: ['Obamba', 'Nzebi', 'Teke'],
      Oyem: ['Fang'],
      Mouila: ['Punu', 'Nzebi'],
      Lambaréné: ['Galoa', 'Fang'],
      Makokou: ['Kota', 'Fang'],
      Tchibanga: ['Punu'],
      Koulamoutou: ['Nzebi', 'Obamba'],
      'Moanda (Haut-Ogooué)': ['Obamba', 'Nzebi', 'Teke'],
    },
    ethnicityLanguages: {
      Fang: ['Fang', 'French'],
      Myene: ['Myene', 'French'],
      Punu: ['Punu', 'French'],
      Nzebi: ['Nzebi', 'French'],
      Obamba: ['Obamba', 'French'],
      Kota: ['Kota', 'French'],
      Teke: ['Teke', 'French'],
      'Baka (Pygmy)': ['Baka', 'French'],
      Galoa: ['Galoa', 'French'],
      'Mixed / Other': ['French'],
    },
    subdivisionLanguages: {
      Estuaire: ['French', 'Fang', 'Myene'],
      'Woleu-Ntem': ['French', 'Fang'],
      'Ogooué-Maritime': ['French', 'Myene'],
      'Haut-Ogooué': ['French', 'Obamba', 'Nzebi'],
      Ngounié: ['French', 'Punu'],
    },
  },
  GQ: {
    ethnicities: [
      'Fang',
      'Bubi',
      'Ndowe',
      'Combe',
      'Bujeba',
      'Annobonese',
      'Fernandino',
      'Mixed / Other',
    ],
    languages: ['Spanish', 'French', 'Portuguese', 'Fang', 'Bube', 'Ndowe', 'Benga'],
    subdivisionEthnicities: {
      'Bioko Norte': ['Bubi', 'Fang', 'Fernandino'],
      'Bioko Sur': ['Bubi', 'Fang'],
      'Centro Sur': ['Fang'],
      Djibloho: ['Fang'],
      'Kié-Ntem': ['Fang'],
      Litoral: ['Fang', 'Ndowe', 'Combe', 'Bujeba'],
      'Wele-Nzas': ['Fang'],
      Annobón: ['Annobonese'],
    },
    cityEthnicities: {
      Malabo: ['Bubi', 'Fang', 'Fernandino'],
      Bata: ['Fang', 'Ndowe', 'Combe'],
      Ebebiyin: ['Fang'],
      Mongomo: ['Fang'],
      Evinayong: ['Fang'],
      Luba: ['Bubi'],
      Mbini: ['Fang', 'Ndowe', 'Combe'],
      'San Antonio de Palé': ['Annobonese'],
    },
    ethnicityLanguages: {
      Fang: ['Fang', 'Spanish', 'French'],
      Bubi: ['Bube', 'Spanish'],
      Ndowe: ['Ndowe', 'Spanish', 'French'],
      Combe: ['Combe', 'Spanish'],
      Bujeba: ['Benga', 'Spanish'],
      Annobonese: ['Annobonese', 'Spanish', 'Portuguese'],
      Fernandino: ['Spanish', 'English'],
      'Mixed / Other': ['Spanish', 'French'],
    },
    subdivisionLanguages: {
      'Bioko Norte': ['Spanish', 'Bube', 'Fang'],
      'Bioko Sur': ['Spanish', 'Bube'],
      Litoral: ['Spanish', 'Fang', 'Ndowe'],
      Annobón: ['Spanish', 'Annobonese'],
    },
  },
};

export const CENTRAL_AFRICA_LANGUAGES: Record<string, readonly string[]> = {
  CD: ['French', 'Swahili', 'Luba-Lulua', 'Lingala', 'Kongo', 'Luba-Katanga'],
  CG: ['French', 'Lingala'],
  CF: ['Sango', 'French'],
  TD: ['Arabic', 'French'],
  GA: ['French', 'Punu'],
  GQ: ['Spanish', 'French', 'Portuguese', 'Fang', 'Bube'],
};
