import { CountryCultureData } from './types';

export const EAST_AFRICA_CULTURE: Record<string, CountryCultureData> = {
  ET: {
    ethnicities: [
      'Amhara',
      'Oromo',
      'Tigrayan',
      'Somali',
      'Sidama',
      'Afar',
      'Gurage',
      'Wolayta',
      'Hadiya',
      'Harari',
      'Anuak',
      'Nuer',
      'Agew',
      'Gamo',
      'Kembata',
      'Silte',
      'Konso',
      'Kafficho',
      'Bench',
      'Dawro',
      'Shinasha',
      'Berta',
      'Mursi',
      'Suri',
      'Karo',
      'Hamer',
      'Borana',
      'Argobba',
      'Arsi',
      'Guji',
    ],
    languages: [
      'Amharic',
      'English',
      'Oromo',
      'Tigrinya',
      'Somali',
      'Sidamo',
      'Afar',
      'Arabic',
      'Gurage',
      'Wolaytta',
      'Hadiyisa',
      'Kambaata',
      'Gamo',
      'Kafficho',
      'Konso',
      'Harari',
      'Nuer',
      'Anuak',
      'Silte',
      'Bench',
    ],
    subdivisionEthnicities: {
      'Addis Ababa': ['Amhara', 'Oromo', 'Gurage'],
      Afar: ['Afar', 'Amhara'],
      Amhara: ['Amhara', 'Agew'],
      'Benishangul-Gumuz': ['Berta', 'Shinasha', 'Amhara', 'Oromo'],
      Dire_Dawa: ['Oromo', 'Somali', 'Amhara'],
      Gambela: ['Anuak', 'Nuer'],
      Harari: ['Harari', 'Oromo', 'Amhara'],
      Oromia: ['Oromo', 'Amhara', 'Borana', 'Arsi', 'Guji'],
      Sidama: ['Sidama', 'Wolayta'],
      SNNPR: ['Wolayta', 'Hadiya', 'Gurage', 'Kembata', 'Silte', 'Kafficho', 'Bench', 'Dawro', 'Konso', 'Gamo'],
      'South West': ['Bench', 'Kafficho', 'Dawro', 'Wolayta', 'Gamo'],
      Somali: ['Somali', 'Oromo'],
      Tigray: ['Tigrayan', 'Amhara'],
    },
    cityEthnicities: {
      'Debre Markos': ['Amhara'],
      'Bahir Dar': ['Amhara'],
      Gondar: ['Amhara'],
      Dessie: ['Amhara'],
      'Debre Birhan': ['Amhara'],
      Adama: ['Oromo', 'Amhara'],
      Jimma: ['Oromo'],
      Bishoftu: ['Oromo', 'Amhara'],
      Mekelle: ['Tigrayan'],
      Harar: ['Harari', 'Oromo'],
      Hawassa: ['Sidama'],
      Jijiga: ['Somali'],
      'Arba Minch': ['Gamo', 'Wolayta'],
      Hosaena: ['Hadiya', 'Kembata'],
      Wolkite: ['Gurage'],
      Assosa: ['Berta', 'Shinasha'],
      Bonga: ['Kafficho', 'Bench'],
      Konso: ['Konso'],
    },
    ethnicityLanguages: {
      Amhara: ['Amharic', 'English'],
      Oromo: ['Oromo', 'Amharic', 'English'],
      Tigrayan: ['Tigrinya', 'Amharic', 'English'],
      Somali: ['Somali', 'Amharic', 'English'],
      Sidama: ['Sidamo', 'Amharic', 'English'],
      Afar: ['Afar', 'Amharic', 'English'],
      Gurage: ['Gurage', 'Amharic', 'English'],
      Wolayta: ['Wolaytta', 'Amharic', 'English'],
      Hadiya: ['Hadiyisa', 'Amharic', 'English'],
      Harari: ['Harari', 'Amharic', 'English'],
      Anuak: ['Amharic', 'English'],
      Nuer: ['Nuer', 'English'],
      Agew: ['Amharic', 'English'],
      Gamo: ['Gamo', 'Amharic', 'English'],
      Kembata: ['Kambaata', 'Amharic', 'English'],
      Silte: ['Silte', 'Amharic', 'English'],
      Konso: ['Konso', 'Amharic', 'English'],
      Kafficho: ['Kafficho', 'Amharic', 'English'],
      Bench: ['Bench', 'Amharic', 'English'],
      Dawro: ['Wolaytta', 'Amharic', 'English'],
      Shinasha: ['Amharic', 'English'],
      Berta: ['Amharic', 'English'],
      Mursi: ['Amharic', 'English'],
      Suri: ['Amharic', 'English'],
      Karo: ['Amharic', 'English'],
      Hamer: ['Amharic', 'English'],
      Borana: ['Oromo', 'Amharic', 'English'],
      Argobba: ['Amharic', 'Arabic', 'English'],
      Arsi: ['Oromo', 'Amharic', 'English'],
      Guji: ['Oromo', 'Amharic', 'English'],
    },
    subdivisionLanguages: {
      Amhara: ['Amharic', 'English'],
      Oromia: ['Oromo', 'Amharic', 'English'],
      Tigray: ['Tigrinya', 'Amharic', 'English'],
      Somali: ['Somali', 'Amharic', 'English'],
      Sidama: ['Sidamo', 'Amharic', 'English'],
      'Benishangul-Gumuz': ['Amharic', 'English'],
      SNNPR: ['Amharic', 'English', 'Wolaytta', 'Hadiyisa', 'Kambaata', 'Gurage'],
      'South West': ['Amharic', 'English', 'Kafficho', 'Bench'],
    },
  },
  KE: {
    ethnicities: ['Kikuyu', 'Luo', 'Luhya', 'Kamba', 'Kalenjin', 'Kisii', 'Meru', 'Mijikenda', 'Maasai', 'Somali'],
    languages: ['English', 'Swahili', 'Kikuyu', 'Luo', 'Kalenjin', 'Kamba', 'Luhya', 'Somali'],
    subdivisionEthnicities: {
      Nairobi: ['Kikuyu', 'Luo', 'Luhya', 'Kamba'],
      Kiambu: ['Kikuyu'],
      Kisumu: ['Luo'],
      Kakamega: ['Luhya'],
      Machakos: ['Kamba'],
      Nyeri: ['Kikuyu'],
      Meru: ['Meru'],
      Garissa: ['Somali'],
      Mombasa: ['Mijikenda', 'Swahili'],
    },
    ethnicityLanguages: {
      Kikuyu: ['Kikuyu', 'Swahili', 'English'],
      Luo: ['Luo', 'Swahili', 'English'],
      Luhya: ['Luhya', 'Swahili', 'English'],
      Kamba: ['Kamba', 'Swahili', 'English'],
      Kalenjin: ['Kalenjin', 'Swahili', 'English'],
      Kisii: ['Kisii', 'Swahili', 'English'],
      Meru: ['Meru', 'Swahili', 'English'],
      Mijikenda: ['Swahili', 'English'],
      Maasai: ['Maa', 'Swahili', 'English'],
      Somali: ['Somali', 'Swahili', 'English'],
    },
  },
  SO: {
    ethnicities: ['Somali', 'Bantu', 'Benadiri', 'Bajuni', 'Arab'],
    languages: ['Somali', 'Arabic', 'English', 'Maay'],
    subdivisionEthnicities: {
      Banadir: ['Somali', 'Benadiri', 'Arab'],
      Puntland: ['Somali'],
      Jubaland: ['Somali', 'Bantu', 'Bajuni'],
      'South West': ['Somali', 'Bantu', 'Maay'],
      Hirshabelle: ['Somali', 'Bantu'],
      Galmudug: ['Somali'],
      Somaliland: ['Somali'],
    },
    cityEthnicities: {
      Mogadishu: ['Somali', 'Benadiri', 'Arab'],
      Kismayo: ['Somali', 'Bajuni', 'Bantu'],
      Baidoa: ['Somali', 'Bantu', 'Maay'],
      Hargeisa: ['Somali'],
      Bosaso: ['Somali'],
      Garowe: ['Somali'],
      Galkayo: ['Somali'],
      Beledweyne: ['Somali', 'Bantu'],
      Jowhar: ['Somali', 'Bantu'],
    },
    ethnicityLanguages: {
      Somali: ['Somali', 'Arabic', 'English'],
      Bantu: ['Maay', 'Somali', 'English'],
      Benadiri: ['Somali', 'Arabic', 'English'],
      Bajuni: ['Somali', 'Arabic', 'English'],
      Arab: ['Arabic', 'Somali', 'English'],
    },
    subdivisionLanguages: {
      Banadir: ['Somali', 'Arabic', 'English'],
      Puntland: ['Somali', 'Arabic', 'English'],
      Jubaland: ['Somali', 'Arabic', 'English'],
      Somaliland: ['Somali', 'Arabic', 'English'],
    },
  },
  UG: {
    ethnicities: ['Baganda', 'Banyankole', 'Basoga', 'Bakiga', 'Itesot', 'Acholi', 'Langi', 'Bagisu', 'Alur', 'Lugbara'],
    languages: ['English', 'Swahili', 'Luganda', 'Runyankole', 'Ateso', 'Acholi', 'Lusoga'],
    subdivisionEthnicities: {
      Central: ['Baganda', 'Basoga'],
      Eastern: ['Basoga', 'Bagisu', 'Itesot'],
      Northern: ['Acholi', 'Langi', 'Alur', 'Lugbara'],
      Western: ['Banyankole', 'Bakiga', 'Batoro', 'Banyoro'],
    },
    ethnicityLanguages: {
      Baganda: ['Luganda', 'English', 'Swahili'],
      Banyankole: ['Runyankole', 'English', 'Swahili'],
      Basoga: ['Lusoga', 'English', 'Swahili'],
      Bakiga: ['Rukiga', 'English', 'Swahili'],
      Itesot: ['Ateso', 'English', 'Swahili'],
      Acholi: ['Acholi', 'English', 'Swahili'],
      Langi: ['Lango', 'English', 'Swahili'],
      Bagisu: ['Lumasaba', 'English', 'Swahili'],
      Alur: ['Alur', 'English', 'Swahili'],
      Lugbara: ['Lugbara', 'English', 'Swahili'],
    },
  },
  TZ: {
    ethnicities: ['Sukuma', 'Chagga', 'Haya', 'Nyakyusa', 'Hehe', 'Makonde', 'Maasai', 'Gogo', 'Ha', 'Zaramo'],
    languages: ['Swahili', 'English', 'Sukuma', 'Chaga', 'Makonde'],
    subdivisionEthnicities: {
      'Dar es Salaam': ['Zaramo', 'Swahili'],
      Mwanza: ['Sukuma'],
      Arusha: ['Maasai', 'Chagga'],
      Kilimanjaro: ['Chagga'],
      Mbeya: ['Nyakyusa'],
      Tanga: ['Shambaa', 'Pare'],
      Zanzibar: ['Swahili', 'Shirazi', 'Arab'],
    },
    ethnicityLanguages: {
      Sukuma: ['Swahili', 'Sukuma', 'English'],
      Chagga: ['Swahili', 'Chaga', 'English'],
      Haya: ['Swahili', 'English'],
      Nyakyusa: ['Swahili', 'English'],
      Hehe: ['Swahili', 'English'],
      Makonde: ['Swahili', 'Makonde', 'English'],
      Maasai: ['Swahili', 'Maa', 'English'],
      Gogo: ['Swahili', 'English'],
      Ha: ['Swahili', 'English'],
      Zaramo: ['Swahili', 'English'],
    },
  },
  RW: {
    ethnicities: ['Hutu', 'Tutsi', 'Twa'],
    languages: ['Kinyarwanda', 'English', 'French', 'Swahili'],
    subdivisionEthnicities: {
      'Kigali City': ['Hutu', 'Tutsi'],
      Eastern: ['Hutu', 'Tutsi'],
      Northern: ['Hutu', 'Tutsi'],
      Southern: ['Hutu', 'Tutsi'],
      Western: ['Hutu', 'Tutsi'],
    },
    ethnicityLanguages: {
      Hutu: ['Kinyarwanda', 'English', 'French', 'Swahili'],
      Tutsi: ['Kinyarwanda', 'English', 'French', 'Swahili'],
      Twa: ['Kinyarwanda', 'English', 'French', 'Swahili'],
    },
  },
  BI: {
    ethnicities: ['Hutu', 'Tutsi', 'Twa'],
    languages: ['Kirundi', 'French', 'English', 'Swahili'],
    ethnicityLanguages: {
      Hutu: ['Kirundi', 'French', 'English', 'Swahili'],
      Tutsi: ['Kirundi', 'French', 'English', 'Swahili'],
      Twa: ['Kirundi', 'French', 'English', 'Swahili'],
    },
  },
  DJ: {
    ethnicities: ['Somali', 'Afar', 'Arab'],
    languages: ['Arabic', 'French', 'Somali', 'Afar', 'English'],
    subdivisionEthnicities: {
      Djibouti: ['Somali', 'Afar', 'Arab'],
      'Ali Sabieh': ['Somali', 'Afar'],
      Dikhil: ['Afar', 'Somali'],
      Obock: ['Afar', 'Arab'],
      Tadjourah: ['Afar', 'Arab'],
    },
    ethnicityLanguages: {
      Somali: ['Somali', 'Arabic', 'French', 'English'],
      Afar: ['Afar', 'Arabic', 'French', 'English'],
      Arab: ['Arabic', 'French', 'English'],
    },
  },
  ER: {
    ethnicities: ['Tigrinya', 'Tigre', 'Saho', 'Afar', 'Kunama', 'Bilen', 'Beja', 'Nara', 'Rashaida'],
    languages: ['Tigrinya', 'Arabic', 'English', 'Tigre', 'Afar'],
    subdivisionEthnicities: {
      Central: ['Tigrinya'],
      Southern: ['Tigrinya'],
      'Northern Red Sea': ['Tigre', 'Beja'],
      'Southern Red Sea': ['Afar', 'Rashaida'],
      Anseba: ['Tigre', 'Bilen'],
      'Gash-Barka': ['Kunama', 'Nara', 'Tigrinya'],
    },
    ethnicityLanguages: {
      Tigrinya: ['Tigrinya', 'Arabic', 'English'],
      Tigre: ['Tigre', 'Arabic', 'English'],
      Saho: ['Saho', 'Arabic', 'English'],
      Afar: ['Afar', 'Arabic', 'English'],
      Kunama: ['Kunama', 'Arabic', 'English'],
      Bilen: ['Bilen', 'Arabic', 'English'],
      Beja: ['Beja', 'Arabic', 'English'],
      Nara: ['Nara', 'Arabic', 'English'],
      Rashaida: ['Arabic', 'English'],
    },
  },
  MG: {
    ethnicities: ['Merina', 'Betsileo', 'Betsimisaraka', 'Sakalava', 'Antandroy', 'Antaimoro', 'Tsimihety', 'Antanosy'],
    languages: ['Malagasy', 'French', 'English'],
    ethnicityLanguages: {
      Merina: ['Malagasy', 'French', 'English'],
      Betsileo: ['Malagasy', 'French', 'English'],
      Betsimisaraka: ['Malagasy', 'French', 'English'],
      Sakalava: ['Malagasy', 'French', 'English'],
      Antandroy: ['Malagasy', 'French', 'English'],
      Antaimoro: ['Malagasy', 'French', 'English'],
      Tsimihety: ['Malagasy', 'French', 'English'],
      Antanosy: ['Malagasy', 'French', 'English'],
    },
  },
};
