import { CountryCultureData } from './types';

export const WEST_AFRICA_CULTURE: Record<string, CountryCultureData> = {
  NG: {
    ethnicities: [
      'Yoruba',
      'Igbo',
      'Hausa',
      'Fulani',
      'Tiv',
      'Kanuri',
      'Ijaw',
      'Edo',
      'Efik',
      'Ibibio',
      'Nupe',
      'Urhobo',
      'Igala',
      'Idoma',
      'Berom',
      'Angas',
      'Jukun',
      'Ebira',
      'Isoko',
      'Itshekiri',
      'Gwari',
      'Mixed / Other',
    ],
    languages: [
      'English',
      'Yoruba',
      'Igbo',
      'Hausa',
      'Fulfulde',
      'Pidgin',
      'Kanuri',
      'Tiv',
      'Edo',
      'Ibibio',
      'Nupe',
      'Urhobo',
      'Igala',
      'Idoma',
      'Ebira',
    ],
    subdivisionEthnicities: {
      Abia: ['Igbo'],
      Adamawa: ['Fulani', 'Hausa', 'Bata'],
      'Akwa Ibom': ['Ibibio', 'Efik', 'Annang'],
      Anambra: ['Igbo'],
      Bauchi: ['Hausa', 'Fulani', 'Angas'],
      Bayelsa: ['Ijaw'],
      Benue: ['Tiv', 'Idoma', 'Igala'],
      Borno: ['Kanuri', 'Fulani', 'Shuwa Arab'],
      'Cross River': ['Efik', 'Ejagham', 'Boki'],
      Delta: ['Urhobo', 'Isoko', 'Itshekiri', 'Ijaw'],
      Ebonyi: ['Igbo'],
      Edo: ['Edo', 'Esan', 'Afemai'],
      Ekiti: ['Yoruba'],
      Enugu: ['Igbo'],
      Gombe: ['Fulani', 'Hausa', 'Tangale'],
      Imo: ['Igbo'],
      Jigawa: ['Hausa', 'Fulani'],
      Kaduna: ['Hausa', 'Fulani', 'Gwari', 'Adara'],
      Kano: ['Hausa', 'Fulani'],
      Katsina: ['Hausa', 'Fulani'],
      Kebbi: ['Hausa', 'Fulani'],
      Kogi: ['Igala', 'Ebira', 'Yoruba'],
      Kwara: ['Yoruba', 'Fulani', 'Nupe'],
      Lagos: ['Yoruba'],
      Nasarawa: ['Eggon', 'Tiv', 'Gwari'],
      Niger: ['Nupe', 'Hausa', 'Gwari'],
      Ogun: ['Yoruba'],
      Ondo: ['Yoruba'],
      Osun: ['Yoruba'],
      Oyo: ['Yoruba'],
      Plateau: ['Berom', 'Angas', 'Hausa', 'Fulani'],
      Rivers: ['Ijaw', 'Ikwerre', 'Ogoni'],
      Sokoto: ['Hausa', 'Fulani'],
      Taraba: ['Jukun', 'Fulani', 'Tiv'],
      Yobe: ['Kanuri', 'Fulani', 'Hausa'],
      Zamfara: ['Hausa', 'Fulani'],
      FCT: ['Hausa', 'Gwari', 'Yoruba', 'Igbo'],
    },
    cityEthnicities: {
      Lagos: ['Yoruba'],
      Ibadan: ['Yoruba'],
      Awka: ['Igbo'],
      Onitsha: ['Igbo'],
      Enugu: ['Igbo'],
      Kano: ['Hausa', 'Fulani'],
      Kaduna: ['Hausa', 'Fulani'],
      'Port Harcourt': ['Ijaw', 'Ikwerre'],
      Abuja: ['Hausa', 'Gwari', 'Yoruba', 'Igbo'],
      'Benin City': ['Edo'],
      Maiduguri: ['Kanuri', 'Fulani', 'Shuwa Arab'],
      Jos: ['Berom', 'Hausa', 'Fulani'],
      Ilorin: ['Yoruba', 'Fulani'],
      Calabar: ['Efik', 'Ibibio'],
      Uyo: ['Ibibio'],
      Sokoto: ['Hausa', 'Fulani'],
      Owerri: ['Igbo'],
      Abeokuta: ['Yoruba'],
      Warri: ['Urhobo', 'Itshekiri', 'Ijaw'],
      Makurdi: ['Tiv', 'Idoma'],
      Zaria: ['Hausa', 'Fulani'],
      Akure: ['Yoruba'],
      Lokoja: ['Igala', 'Ebira', 'Yoruba'],
      Yola: ['Fulani', 'Hausa'],
      Gombe: ['Fulani', 'Hausa', 'Tangale'],
    },
    ethnicityLanguages: {
      Yoruba: ['Yoruba', 'English'],
      Igbo: ['Igbo', 'English'],
      Hausa: ['Hausa', 'English'],
      Fulani: ['Fulfulde', 'Hausa', 'English'],
      Tiv: ['Tiv', 'English'],
      Kanuri: ['Kanuri', 'English'],
      Ijaw: ['English', 'Pidgin'],
      Edo: ['Edo', 'English'],
      Efik: ['Efik', 'English'],
      Ibibio: ['Ibibio', 'English'],
      Nupe: ['Nupe', 'English'],
      Urhobo: ['Urhobo', 'English'],
      Igala: ['Igala', 'English'],
      Idoma: ['Idoma', 'English'],
      Berom: ['Berom', 'English'],
      Angas: ['Angas', 'Hausa', 'English'],
      Jukun: ['Jukun', 'English'],
      Ebira: ['Ebira', 'English'],
      Isoko: ['Isoko', 'English'],
      Itshekiri: ['Itshekiri', 'English'],
      Gwari: ['Gwari', 'Hausa', 'English'],
      'Mixed / Other': ['English', 'Pidgin'],
    },
    subdivisionLanguages: {
      Kano: ['Hausa', 'English'],
      Lagos: ['Yoruba', 'English', 'Pidgin'],
      Anambra: ['Igbo', 'English'],
      Borno: ['Kanuri', 'Hausa', 'English'],
      Rivers: ['English', 'Pidgin', 'Ijaw'],
      Kaduna: ['Hausa', 'English'],
      Benue: ['Tiv', 'Idoma', 'English'],
      Delta: ['Urhobo', 'Isoko', 'English'],
    },
  },
  GH: {
    ethnicities: [
      'Akan',
      'Ewe',
      'Ga',
      'Dagomba',
      'Gurma',
      'Guan',
      'Fante',
      'Ashanti',
      'Mole-Dagbani',
      'Grusi',
      'Dagaaba',
      'Mamprusi',
      'Konkomba',
      'Hausa',
      'Mixed / Other',
    ],
    languages: ['English', 'Twi', 'Ga', 'Ewe', 'Fante', 'Dagbani', 'Hausa', 'Nzema', 'Dagaare'],
    subdivisionEthnicities: {
      'Greater Accra': ['Ga', 'Akan', 'Ewe'],
      Ashanti: ['Ashanti', 'Akan'],
      Central: ['Fante', 'Akan'],
      Volta: ['Ewe', 'Guan'],
      Northern: ['Dagomba', 'Mamprusi', 'Konkomba'],
      'Upper East': ['Grusi', 'Mole-Dagbani'],
      'Upper West': ['Dagaaba', 'Grusi'],
      'Bono East': ['Akan'],
      'Bono': ['Akan'],
      Ahafo: ['Akan'],
      Eastern: ['Akan', 'Guan'],
      Savannah: ['Mole-Dagbani'],
      'North East': ['Mamprusi', 'Dagomba'],
      Oti: ['Guan', 'Ewe', 'Konkomba'],
      Western: ['Akan', 'Nzema'],
      'Western North': ['Akan', 'Nzema'],
    },
    cityEthnicities: {
      Accra: ['Ga', 'Akan', 'Ewe'],
      Kumasi: ['Ashanti', 'Akan'],
      Tamale: ['Dagomba'],
      'Cape Coast': ['Fante', 'Akan'],
      Ho: ['Ewe'],
      Sunyani: ['Akan'],
      Sekondi: ['Akan', 'Nzema'],
      Takoradi: ['Akan', 'Nzema'],
      Bolgatanga: ['Grusi'],
      Wa: ['Dagaaba', 'Grusi'],
      Koforidua: ['Akan', 'Guan'],
      Navrongo: ['Grusi'],
      Nalerigu: ['Mamprusi'],
    },
    ethnicityLanguages: {
      Akan: ['Twi', 'English'],
      Ewe: ['Ewe', 'English'],
      Ga: ['Ga', 'English'],
      Dagomba: ['Dagbani', 'English'],
      Gurma: ['Gurma', 'English'],
      Guan: ['Guan', 'English'],
      Fante: ['Fante', 'English'],
      Ashanti: ['Twi', 'English'],
      'Mole-Dagbani': ['Dagbani', 'English'],
      Grusi: ['Grusi', 'English'],
      Dagaaba: ['Dagaare', 'English'],
      Mamprusi: ['Mampruli', 'English'],
      Konkomba: ['Konkomba', 'English'],
      Hausa: ['Hausa', 'English'],
      'Mixed / Other': ['English', 'Twi'],
    },
    subdivisionLanguages: {
      'Greater Accra': ['English', 'Ga', 'Twi'],
      Ashanti: ['Twi', 'English'],
      Northern: ['Dagbani', 'English'],
      Volta: ['Ewe', 'English'],
      Central: ['Fante', 'English'],
      'Upper West': ['Dagaare', 'English'],
    },
  },
  SN: {
    ethnicities: [
      'Wolof',
      'Serer',
      'Fula',
      'Jola',
      'Mandinka',
      'Soninke',
      'Badiaranke',
      'Bassari',
      'Lebou',
      'Balanta',
      'Mixed / Other',
    ],
    languages: ['French', 'Wolof', 'Serer', 'Fula', 'Mandinka', 'Jola', 'Soninke'],
    subdivisionEthnicities: {
      Dakar: ['Wolof', 'Lebou', 'Serer'],
      Diourbel: ['Wolof', 'Serer'],
      Fatick: ['Serer', 'Wolof'],
      Kaffrine: ['Wolof', 'Mandinka', 'Fula'],
      Kaolack: ['Wolof', 'Serer', 'Fula'],
      Kédougou: ['Mandinka', 'Bassari', 'Fula'],
      Kolda: ['Fula', 'Mandinka', 'Jola'],
      Louga: ['Wolof', 'Fula'],
      Matam: ['Fula', 'Soninke'],
      'Saint-Louis': ['Wolof', 'Fula'],
      Sédhiou: ['Mandinka', 'Balanta', 'Fula'],
      Tambacounda: ['Mandinka', 'Fula', 'Wolof', 'Bassari'],
      Thiès: ['Wolof', 'Serer'],
      Ziguinchor: ['Jola', 'Mandinka', 'Balanta'],
    },
    cityEthnicities: {
      Dakar: ['Wolof', 'Lebou', 'Serer'],
      Thiès: ['Wolof', 'Serer'],
      Kaolack: ['Wolof', 'Serer', 'Fula'],
      Ziguinchor: ['Jola', 'Mandinka'],
      'Saint-Louis': ['Wolof', 'Fula'],
      Touba: ['Wolof'],
      Kolda: ['Fula', 'Mandinka'],
      Tambacounda: ['Mandinka', 'Fula'],
      Louga: ['Wolof', 'Fula'],
      Diourbel: ['Wolof'],
    },
    ethnicityLanguages: {
      Wolof: ['Wolof', 'French'],
      Serer: ['Serer', 'Wolof', 'French'],
      Fula: ['Fula', 'Wolof', 'French'],
      Jola: ['Jola', 'French'],
      Mandinka: ['Mandinka', 'Wolof', 'French'],
      Soninke: ['Soninke', 'Wolof', 'French'],
      Badiaranke: ['Badiaranke', 'French'],
      Bassari: ['Bassari', 'French'],
      Lebou: ['Wolof', 'French'],
      Balanta: ['Balanta', 'French'],
      'Mixed / Other': ['French', 'Wolof'],
    },
    subdivisionLanguages: {
      Dakar: ['Wolof', 'French'],
      Ziguinchor: ['Jola', 'Mandinka', 'French'],
      'Saint-Louis': ['Wolof', 'French'],
      Tambacounda: ['Mandinka', 'French'],
      Matam: ['Fula', 'French'],
    },
  },
  CI: {
    ethnicities: [
      'Akan (Baoulé)',
      'Akan (Agni)',
      'Krou (Bété)',
      'Krou (Dida)',
      'Mandé (Malinké)',
      'Mandé (Dan)',
      'Gur (Senufo)',
      'Gur (Lobi)',
      'Lagoon (Attié)',
      'Lagoon (Ebrié)',
      'Guro',
      'Dyula',
      'Mixed / Other',
    ],
    languages: ['French', 'Baoulé', 'Bété', 'Dioula', 'Senufo', 'Malinké', 'Dan'],
    subdivisionEthnicities: {
      Abidjan: ['Akan (Baoulé)', 'Lagoon (Ebrié)', 'Lagoon (Attié)', 'Dyula'],
      Bas_Sassandra: ['Krou (Bété)', 'Krou (Dida)'],
      Comoé: ['Akan (Agni)', 'Lagoon (Attié)'],
      Denguélé: ['Mandé (Malinké)', 'Dyula'],
      Gôh_Djiboua: ['Krou (Bété)', 'Guro'],
      Lacs: ['Akan (Baoulé)', 'Lagoon (Attié)'],
      Lagunes: ['Lagoon (Ebrié)', 'Lagoon (Attié)', 'Akan (Agni)'],
      Montagnes: ['Mandé (Dan)', 'Guro'],
      Sassandra_Marahoué: ['Krou (Bété)', 'Guro'],
      Savanes: ['Gur (Senufo)', 'Dyula'],
      'Vallée du Bandama': ['Akan (Baoulé)', 'Gur (Senufo)'],
      Woroba: ['Mandé (Malinké)', 'Gur (Senufo)'],
      Yamoussoukro: ['Akan (Baoulé)'],
      Zanzan: ['Akan (Agni)', 'Gur (Lobi)'],
    },
    cityEthnicities: {
      Abidjan: ['Akan (Baoulé)', 'Lagoon (Ebrié)', 'Lagoon (Attié)', 'Dyula'],
      Yamoussoukro: ['Akan (Baoulé)'],
      Bouaké: ['Akan (Baoulé)', 'Dyula'],
      Daloa: ['Krou (Bété)'],
      Korhogo: ['Gur (Senufo)', 'Dyula'],
      Man: ['Mandé (Dan)'],
      'San-Pédro': ['Krou (Bété)', 'Krou (Dida)'],
      Gagnoa: ['Krou (Bété)', 'Guro'],
      Abengourou: ['Akan (Agni)'],
      Bondoukou: ['Akan (Agni)', 'Gur (Lobi)'],
    },
    ethnicityLanguages: {
      'Akan (Baoulé)': ['Baoulé', 'Dioula', 'French'],
      'Akan (Agni)': ['Agni', 'Dioula', 'French'],
      'Krou (Bété)': ['Bété', 'French'],
      'Krou (Dida)': ['Dida', 'French'],
      'Mandé (Malinké)': ['Malinké', 'Dioula', 'French'],
      'Mandé (Dan)': ['Dan', 'French'],
      'Gur (Senufo)': ['Senufo', 'Dioula', 'French'],
      'Gur (Lobi)': ['Lobi', 'French'],
      'Lagoon (Attié)': ['Attié', 'French'],
      'Lagoon (Ebrié)': ['Ebrié', 'French'],
      Guro: ['Guro', 'French'],
      Dyula: ['Dioula', 'French'],
      'Mixed / Other': ['French', 'Dioula'],
    },
    subdivisionLanguages: {
      Abidjan: ['French', 'Dioula'],
      Savanes: ['Senufo', 'Dioula', 'French'],
      Denguélé: ['Malinké', 'Dioula', 'French'],
      Montagnes: ['Dan', 'French'],
      Bas_Sassandra: ['Bété', 'French'],
    },
  },
  ML: {
    ethnicities: [
      'Bambara',
      'Fulani',
      'Songhai',
      'Tuareg',
      'Soninke',
      'Senufo',
      'Dogon',
      'Bozo',
      'Bobo',
      'Malinké',
      'Khassonké',
      'Mixed / Other',
    ],
    languages: ['French', 'Bambara', 'Fula', 'Songhai', 'Tamasheq', 'Soninke', 'Dogon', 'Senufo'],
    subdivisionEthnicities: {
      Bamako: ['Bambara', 'Malinké', 'Mixed / Other'],
      Kayes: ['Khassonké', 'Malinké', 'Soninke', 'Fulani'],
      Koulikoro: ['Bambara', 'Malinké'],
      Sikasso: ['Senufo', 'Bambara', 'Fulani'],
      Ségou: ['Bambara', 'Bozo', 'Fulani'],
      Mopti: ['Dogon', 'Fulani', 'Bozo', 'Bambara'],
      Tombouctou: ['Songhai', 'Tuareg', 'Fulani'],
      Gao: ['Songhai', 'Tuareg'],
      Kidal: ['Tuareg', 'Songhai'],
      Taoudénit: ['Tuareg', 'Songhai'],
      Ménaka: ['Tuareg', 'Songhai'],
    },
    cityEthnicities: {
      Bamako: ['Bambara', 'Malinké', 'Mixed / Other'],
      Kayes: ['Khassonké', 'Soninke', 'Malinké'],
      Sikasso: ['Senufo', 'Bambara'],
      Ségou: ['Bambara', 'Bozo'],
      Mopti: ['Dogon', 'Fulani', 'Bozo'],
      Gao: ['Songhai', 'Tuareg'],
      Tombouctou: ['Songhai', 'Tuareg'],
      Kidal: ['Tuareg'],
      Koulikoro: ['Bambara', 'Malinké'],
      Kita: ['Malinké'],
    },
    ethnicityLanguages: {
      Bambara: ['Bambara', 'French'],
      Fulani: ['Fula', 'Bambara', 'French'],
      Songhai: ['Songhai', 'French'],
      Tuareg: ['Tamasheq', 'French'],
      Soninke: ['Soninke', 'Bambara', 'French'],
      Senufo: ['Senufo', 'Bambara', 'French'],
      Dogon: ['Dogon', 'Bambara', 'French'],
      Bozo: ['Bozo', 'Bambara', 'French'],
      Bobo: ['Bobo', 'French'],
      Malinké: ['Malinké', 'Bambara', 'French'],
      Khassonké: ['Khassonké', 'Bambara', 'French'],
      'Mixed / Other': ['French', 'Bambara'],
    },
    subdivisionLanguages: {
      Bamako: ['Bambara', 'French'],
      Kidal: ['Tamasheq', 'French'],
      Tombouctou: ['Songhai', 'Tamasheq', 'French'],
      Mopti: ['Dogon', 'Fula', 'Bambara', 'French'],
      Kayes: ['Malinké', 'Soninke', 'French'],
    },
  },
  BF: {
    ethnicities: [
      'Mossi',
      'Fulani',
      'Bobo',
      'Gurma',
      'Senufo',
      'Lobi',
      'Dagara',
      'Bissa',
      'Gourmantché',
      'Samo',
      'Marka',
      'Mixed / Other',
    ],
    languages: ['French', 'Moore', 'Dioula', 'Fula', 'Gulmancema', 'Bissa', 'Dagaare'],
    subdivisionEthnicities: {
      'Centre (Ouagadougou)': ['Mossi', 'Mixed / Other'],
      'Boucle du Mouhoun': ['Marka', 'Samo', 'Bissa'],
      Cascades: ['Senufo', 'Bobo', 'Fulani'],
      Centre_Est: ['Mossi', 'Gourmantché'],
      Centre_Nord: ['Mossi', 'Fulani'],
      Centre_Ouest: ['Mossi', 'Gourmantché'],
      Centre_Sud: ['Mossi'],
      Est: ['Gourmantché', 'Mossi', 'Fulani'],
      'Hauts-Bassins': ['Bobo', 'Fulani', 'Senufo'],
      Nord: ['Mossi', 'Fulani'],
      'Plateau-Central': ['Mossi'],
      Sahel: ['Fulani', 'Mossi', 'Gourmantché'],
      'Sud-Ouest': ['Dagara', 'Lobi', 'Bobo'],
    },
    cityEthnicities: {
      Ouagadougou: ['Mossi', 'Mixed / Other'],
      Bobo_Dioulasso: ['Bobo', 'Dioula', 'Fulani'],
      Koudougou: ['Mossi'],
      Ouahigouya: ['Mossi', 'Fulani'],
      Banfora: ['Senufo', 'Bobo'],
      Fada_Ngourma: ['Gourmantché', 'Mossi'],
      Dori: ['Fulani'],
      Tenkodogo: ['Mossi', 'Gourmantché'],
      Gaoua: ['Lobi', 'Dagara'],
    },
    ethnicityLanguages: {
      Mossi: ['Moore', 'French'],
      Fulani: ['Fula', 'Moore', 'French'],
      Bobo: ['Bobo', 'Dioula', 'French'],
      Gurma: ['Gulmancema', 'Moore', 'French'],
      Senufo: ['Senufo', 'Dioula', 'French'],
      Lobi: ['Lobi', 'French'],
      Dagara: ['Dagaare', 'French'],
      Bissa: ['Bissa', 'Moore', 'French'],
      Gourmantché: ['Gulmancema', 'Moore', 'French'],
      Samo: ['Samo', 'French'],
      Marka: ['Marka', 'Dioula', 'French'],
      'Mixed / Other': ['French', 'Moore', 'Dioula'],
    },
    subdivisionLanguages: {
      'Centre (Ouagadougou)': ['Moore', 'French'],
      'Hauts-Bassins': ['Dioula', 'French', 'Bobo'],
      Sahel: ['Fula', 'French'],
      Est: ['Gulmancema', 'Moore', 'French'],
      'Sud-Ouest': ['Dagaare', 'Lobi', 'French'],
    },
  },
  NE: {
    ethnicities: [
      'Hausa',
      'Zarma',
      'Tuareg',
      'Fulani',
      'Kanuri',
      'Toubou',
      'Gourmantché',
      'Arab Nigerien',
      'Mixed / Other',
    ],
    languages: ['French', 'Hausa', 'Zarma', 'Tamasheq', 'Fula', 'Kanuri'],
    subdivisionEthnicities: {
      Niamey: ['Zarma', 'Hausa', 'Fulani'],
      Agadez: ['Tuareg', 'Hausa'],
      Diffa: ['Kanuri', 'Toubou', 'Fulani'],
      Dosso: ['Zarma', 'Fulani'],
      Maradi: ['Hausa', 'Fulani'],
      Tahoua: ['Hausa', 'Tuareg', 'Fulani'],
      Tillabéri: ['Zarma', 'Fulani', 'Gourmantché'],
      Zinder: ['Hausa', 'Tuareg'],
    },
    cityEthnicities: {
      Niamey: ['Zarma', 'Hausa', 'Fulani'],
      Zinder: ['Hausa', 'Tuareg'],
      Maradi: ['Hausa', 'Fulani'],
      Agadez: ['Tuareg', 'Hausa'],
      Tahoua: ['Hausa', 'Tuareg'],
      Dosso: ['Zarma'],
      Diffa: ['Kanuri'],
      Tillabéri: ['Zarma'],
    },
    ethnicityLanguages: {
      Hausa: ['Hausa', 'French'],
      Zarma: ['Zarma', 'Hausa', 'French'],
      Tuareg: ['Tamasheq', 'Hausa', 'French'],
      Fulani: ['Fula', 'Hausa', 'French'],
      Kanuri: ['Kanuri', 'Hausa', 'French'],
      Toubou: ['Toubou', 'French'],
      Gourmantché: ['Gulmancema', 'French'],
      'Arab Nigerien': ['Arabic', 'Hausa', 'French'],
      'Mixed / Other': ['French', 'Hausa'],
    },
    subdivisionLanguages: {
      Niamey: ['Zarma', 'French'],
      Maradi: ['Hausa', 'French'],
      Agadez: ['Tamasheq', 'French'],
      Zinder: ['Hausa', 'French'],
      Diffa: ['Kanuri', 'French'],
    },
  },
  BJ: {
    ethnicities: [
      'Fon',
      'Yoruba',
      'Adja',
      'Bariba',
      'Fulani',
      'Somba (Bétamaribè)',
      'Dendi',
      'Mina',
      'Mixed / Other',
    ],
    languages: ['French', 'Fon', 'Yoruba', 'Adja', 'Bariba', 'Fula', 'Dendi'],
    subdivisionEthnicities: {
      Alibori: ['Bariba', 'Fulani', 'Dendi'],
      Atakora: ['Somba (Bétamaribè)', 'Bariba'],
      Atlantique: ['Fon', 'Yoruba', 'Adja'],
      Borgou: ['Bariba', 'Fulani', 'Dendi'],
      Collines: ['Yoruba', 'Bariba', 'Fon'],
      Couffo: ['Adja', 'Fon'],
      Donga: ['Bariba', 'Fulani', 'Yoruba'],
      Littoral: ['Fon', 'Yoruba', 'Goun'],
      Mono: ['Mina', 'Adja', 'Fon'],
      Ouémé: ['Yoruba', 'Fon', 'Goun'],
      Plateau: ['Yoruba', 'Adja', 'Fon'],
      Zou: ['Fon', 'Yoruba', 'Adja'],
    },
    cityEthnicities: {
      Cotonou: ['Fon', 'Yoruba', 'Goun'],
      'Porto-Novo': ['Yoruba', 'Fon', 'Goun'],
      Parakou: ['Bariba', 'Dendi', 'Fulani'],
      Abomey: ['Fon'],
      Natitingou: ['Somba (Bétamaribè)', 'Bariba'],
      Lokossa: ['Mina', 'Adja', 'Fon'],
      Djougou: ['Bariba', 'Fulani', 'Yoruba'],
      Bohicon: ['Fon'],
      Ouidah: ['Fon', 'Yoruba'],
    },
    ethnicityLanguages: {
      Fon: ['Fon', 'French'],
      Yoruba: ['Yoruba', 'Fon', 'French'],
      Adja: ['Adja', 'Fon', 'French'],
      Bariba: ['Bariba', 'Dendi', 'French'],
      Fulani: ['Fula', 'French'],
      'Somba (Bétamaribè)': ['Bétamaribè', 'French'],
      Dendi: ['Dendi', 'Bariba', 'French'],
      Mina: ['Mina', 'Fon', 'French'],
      'Mixed / Other': ['French', 'Fon'],
    },
    subdivisionLanguages: {
      Littoral: ['Fon', 'French', 'Yoruba'],
      Alibori: ['Bariba', 'Dendi', 'French'],
      Atakora: ['Bétamaribè', 'French'],
      Ouémé: ['Yoruba', 'Fon', 'French'],
    },
  },
  TG: {
    ethnicities: ['Ewe', 'Kabye', 'Tem', 'Gourma', 'Moba', 'Akposso', 'Ana', 'Bassar', 'Mixed / Other'],
    languages: ['French', 'Ewe', 'Kabye', 'Tem', 'Moba'],
    subdivisionEthnicities: {
      Maritime: ['Ewe', 'Mina', 'Ana'],
      Plateaux: ['Ewe', 'Akposso', 'Ana'],
      Centrale: ['Tem', 'Kabye'],
      Kara: ['Kabye', 'Bassar'],
      Savanes: ['Moba', 'Gourma'],
    },
    cityEthnicities: {
      Lomé: ['Ewe', 'Mina'],
      Kara: ['Kabye', 'Bassar'],
      Sokodé: ['Tem', 'Kabye'],
      Atakpamé: ['Ewe', 'Akposso'],
      Dapaong: ['Moba', 'Gourma'],
      Kpalimé: ['Ewe'],
      Bassar: ['Bassar', 'Kabye'],
    },
    ethnicityLanguages: {
      Ewe: ['Ewe', 'French'],
      Kabye: ['Kabye', 'French'],
      Tem: ['Tem', 'Kabye', 'French'],
      Gourma: ['Gourma', 'French'],
      Moba: ['Moba', 'French'],
      Akposso: ['Akposso', 'Ewe', 'French'],
      Ana: ['Ana', 'Ewe', 'French'],
      Bassar: ['Bassar', 'French'],
      'Mixed / Other': ['French', 'Ewe'],
    },
    subdivisionLanguages: {
      Maritime: ['Ewe', 'French', 'Mina'],
      Kara: ['Kabye', 'French'],
      Savanes: ['Moba', 'French'],
    },
  },
  GN: {
    ethnicities: [
      'Fulani',
      'Malinké',
      'Susu',
      'Guerzé',
      'Toma',
      'Kissi',
      'Kono',
      'Baga',
      'Landouma',
      'Mixed / Other',
    ],
    languages: ['French', 'Fula', 'Malinké', 'Susu', 'Guerzé', 'Toma', 'Kissi'],
    subdivisionEthnicities: {
      Conakry: ['Susu', 'Malinké', 'Fulani'],
      Boké: ['Landouma', 'Baga', 'Susu'],
      Kindia: ['Susu', 'Fulani', 'Malinké'],
      Mamou: ['Fulani', 'Malinké'],
      Labé: ['Fulani'],
      Faranah: ['Malinké', 'Fulani'],
      Kankan: ['Malinké'],
      Nzérékoré: ['Guerzé', 'Toma', 'Kono'],
    },
    cityEthnicities: {
      Conakry: ['Susu', 'Malinké', 'Fulani'],
      Nzérékoré: ['Guerzé', 'Toma'],
      Kankan: ['Malinké'],
      Labé: ['Fulani'],
      Kindia: ['Susu', 'Fulani'],
      Mamou: ['Fulani', 'Malinké'],
      Boké: ['Landouma', 'Baga'],
      Faranah: ['Malinké', 'Fulani'],
    },
    ethnicityLanguages: {
      Fulani: ['Fula', 'French'],
      Malinké: ['Malinké', 'French'],
      Susu: ['Susu', 'French'],
      Guerzé: ['Guerzé', 'French'],
      Toma: ['Toma', 'French'],
      Kissi: ['Kissi', 'French'],
      Kono: ['Kono', 'French'],
      Baga: ['Baga', 'Susu', 'French'],
      Landouma: ['Landouma', 'Susu', 'French'],
      'Mixed / Other': ['French', 'Susu'],
    },
    subdivisionLanguages: {
      Conakry: ['Susu', 'French', 'Malinké'],
      Labé: ['Fula', 'French'],
      Kankan: ['Malinké', 'French'],
      Nzérékoré: ['Guerzé', 'Toma', 'French'],
    },
  },
  SL: {
    ethnicities: [
      'Temne',
      'Mende',
      'Limba',
      'Krio',
      'Loko',
      'Sherbro',
      'Kissi',
      'Kono',
      'Susu',
      'Fulani',
      'Mandingo',
      'Mixed / Other',
    ],
    languages: ['English', 'Krio', 'Temne', 'Mende', 'Limba', 'Kono'],
    subdivisionEthnicities: {
      'Western Area': ['Krio', 'Temne', 'Mende', 'Limba'],
      Northern: ['Temne', 'Limba', 'Loko', 'Susu'],
      Eastern: ['Mende', 'Kissi', 'Kono'],
      Southern: ['Mende', 'Sherbro'],
      'North Western': ['Temne', 'Limba', 'Susu'],
    },
    cityEthnicities: {
      Freetown: ['Krio', 'Temne', 'Mende', 'Limba'],
      Bo: ['Mende'],
      Kenema: ['Mende'],
      Makeni: ['Temne', 'Limba'],
      Koidu: ['Kono', 'Mende'],
      Port_Loko: ['Temne', 'Susu'],
      Kabala: ['Limba', 'Fulani'],
    },
    ethnicityLanguages: {
      Temne: ['Temne', 'Krio', 'English'],
      Mende: ['Mende', 'Krio', 'English'],
      Limba: ['Limba', 'Krio', 'English'],
      Krio: ['Krio', 'English'],
      Loko: ['Loko', 'Krio', 'English'],
      Sherbro: ['Sherbro', 'Krio', 'English'],
      Kissi: ['Kissi', 'Mende', 'English'],
      Kono: ['Kono', 'Krio', 'English'],
      Susu: ['Susu', 'Krio', 'English'],
      Fulani: ['Fula', 'Krio', 'English'],
      Mandingo: ['Mandinka', 'Krio', 'English'],
      'Mixed / Other': ['Krio', 'English'],
    },
    subdivisionLanguages: {
      'Western Area': ['Krio', 'English', 'Temne'],
      Northern: ['Temne', 'Krio', 'English'],
      Eastern: ['Mende', 'Krio', 'English'],
      Southern: ['Mende', 'Krio', 'English'],
    },
  },
  LR: {
    ethnicities: [
      'Kpelle',
      'Bassa',
      'Grebo',
      'Gio',
      'Mano',
      'Kru',
      'Loma',
      'Kissi',
      'Americo-Liberian',
      'Vai',
      'Mandingo',
      'Krahn',
      'Mixed / Other',
    ],
    languages: ['English', 'Kpelle', 'Bassa', 'Kru', 'Vai', 'Mano'],
    subdivisionEthnicities: {
      Montserrado: ['Americo-Liberian', 'Kpelle', 'Bassa', 'Kru'],
      Bomi: ['Kpelle', 'Gola'],
      Bong: ['Kpelle'],
      Gbarpolu: ['Kpelle', 'Gola'],
      'Grand Bassa': ['Bassa'],
      'Grand Cape Mount': ['Vai', 'Gola'],
      'Grand Gedeh': ['Krahn'],
      'Grand Kru': ['Kru', 'Grebo'],
      Lofa: ['Loma', 'Kissi', 'Mandingo'],
      Margibi: ['Kpelle', 'Bassa'],
      Maryland: ['Grebo'],
      Nimba: ['Gio', 'Mano'],
      'River Cess': ['Bassa', 'Kru'],
      'River Gee': ['Grebo'],
      Sinoe: ['Kru'],
    },
    cityEthnicities: {
      Monrovia: ['Americo-Liberian', 'Kpelle', 'Bassa', 'Kru'],
      Gbarnga: ['Kpelle'],
      Buchanan: ['Bassa'],
      Harper: ['Grebo'],
      Voinjama: ['Loma', 'Mandingo'],
      Sanniquellie: ['Gio', 'Mano'],
      Zwedru: ['Krahn'],
      Robertsport: ['Vai', 'Gola'],
      Greenville: ['Kru'],
    },
    ethnicityLanguages: {
      Kpelle: ['Kpelle', 'English'],
      Bassa: ['Bassa', 'English'],
      Grebo: ['Grebo', 'English'],
      Gio: ['Gio', 'English'],
      Mano: ['Mano', 'English'],
      Kru: ['Kru', 'English'],
      Loma: ['Loma', 'English'],
      Kissi: ['Kissi', 'English'],
      'Americo-Liberian': ['English'],
      Vai: ['Vai', 'English'],
      Mandingo: ['Mandinka', 'English'],
      Krahn: ['Krahn', 'English'],
      'Mixed / Other': ['English'],
    },
    subdivisionLanguages: {
      Montserrado: ['English', 'Kpelle', 'Bassa'],
      Nimba: ['Gio', 'Mano', 'English'],
      Lofa: ['Loma', 'English'],
      'Grand Bassa': ['Bassa', 'English'],
    },
  },
  GW: {
    ethnicities: [
      'Balanta',
      'Fula',
      'Manjaco',
      'Mandinka',
      'Papel',
      'Mancanha',
      'Beafada',
      'Bijagó',
      'Mixed / Other',
    ],
    languages: ['Portuguese', 'Guinea-Bissau Creole', 'Balanta', 'Fula', 'Mandinka', 'Manjaco'],
    subdivisionEthnicities: {
      Bissau: ['Balanta', 'Papel', 'Manjaco', 'Mandinka'],
      Bafatá: ['Mandinka', 'Fula', 'Balanta'],
      Biombo: ['Balanta', 'Papel'],
      Bolama: ['Bijagó', 'Balanta'],
      Cacheu: ['Manjaco', 'Mancanha'],
      Gabú: ['Fula', 'Mandinka'],
      Oio: ['Balanta', 'Mandinka', 'Fula'],
      Quinara: ['Beafada', 'Balanta'],
      Tombali: ['Balanta', 'Fula'],
    },
    cityEthnicities: {
      Bissau: ['Balanta', 'Papel', 'Manjaco', 'Mandinka'],
      Bafatá: ['Mandinka', 'Fula', 'Balanta'],
      Gabú: ['Fula', 'Mandinka'],
      Canchungo: ['Manjaco', 'Mancanha'],
      Buba: ['Beafada', 'Balanta'],
      Cacheu: ['Manjaco'],
    },
    ethnicityLanguages: {
      Balanta: ['Balanta', 'Guinea-Bissau Creole', 'Portuguese'],
      Fula: ['Fula', 'Guinea-Bissau Creole', 'Portuguese'],
      Manjaco: ['Manjaco', 'Guinea-Bissau Creole', 'Portuguese'],
      Mandinka: ['Mandinka', 'Guinea-Bissau Creole', 'Portuguese'],
      Papel: ['Papel', 'Guinea-Bissau Creole', 'Portuguese'],
      Mancanha: ['Mancanha', 'Guinea-Bissau Creole', 'Portuguese'],
      Beafada: ['Beafada', 'Guinea-Bissau Creole', 'Portuguese'],
      Bijagó: ['Bijagó', 'Guinea-Bissau Creole', 'Portuguese'],
      'Mixed / Other': ['Guinea-Bissau Creole', 'Portuguese'],
    },
    subdivisionLanguages: {
      Bissau: ['Guinea-Bissau Creole', 'Portuguese'],
      Gabú: ['Fula', 'Guinea-Bissau Creole', 'Portuguese'],
      Cacheu: ['Manjaco', 'Guinea-Bissau Creole', 'Portuguese'],
    },
  },
  GM: {
    ethnicities: [
      'Mandinka',
      'Wolof',
      'Fula',
      'Jola',
      'Serahuli',
      'Serer',
      'Manjago',
      'Aku',
      'Mixed / Other',
    ],
    languages: ['English', 'Mandinka', 'Wolof', 'Fula', 'Jola', 'Serahuli'],
    subdivisionEthnicities: {
      Banjul: ['Aku', 'Wolof', 'Mandinka'],
      'Central River': ['Mandinka', 'Fula'],
      'Lower River': ['Mandinka', 'Jola'],
      'North Bank': ['Mandinka', 'Wolof'],
      'Upper River': ['Mandinka', 'Serahuli', 'Fula'],
      'West Coast': ['Jola', 'Mandinka', 'Manjago'],
    },
    cityEthnicities: {
      Banjul: ['Aku', 'Wolof', 'Mandinka'],
      Serekunda: ['Mandinka', 'Wolof', 'Jola'],
      Brikama: ['Jola', 'Mandinka'],
      Basse: ['Mandinka', 'Serahuli', 'Fula'],
      Farafenni: ['Mandinka', 'Wolof'],
      Janjanbureh: ['Mandinka', 'Fula'],
    },
    ethnicityLanguages: {
      Mandinka: ['Mandinka', 'English'],
      Wolof: ['Wolof', 'Mandinka', 'English'],
      Fula: ['Fula', 'Mandinka', 'English'],
      Jola: ['Jola', 'Mandinka', 'English'],
      Serahuli: ['Serahuli', 'Mandinka', 'English'],
      Serer: ['Serer', 'Mandinka', 'English'],
      Manjago: ['Manjago', 'English'],
      Aku: ['English'],
      'Mixed / Other': ['English', 'Mandinka'],
    },
    subdivisionLanguages: {
      Banjul: ['English', 'Mandinka', 'Wolof'],
      'Upper River': ['Mandinka', 'Serahuli', 'English'],
    },
  },
  CV: {
    ethnicities: [
      'Creole / Mestiço',
      'African (Badio)',
      'Portuguese European',
      'Mixed / Other',
    ],
    languages: ['Portuguese', 'Cape Verdean Creole'],
    subdivisionEthnicities: {
      'Ilhas de Barlavento':
        ['Creole / Mestiço', 'African (Badio)', 'Portuguese European'],
      'Ilhas de Sotavento':
        ['Creole / Mestiço', 'African (Badio)', 'Portuguese European'],
    },
    cityEthnicities: {
      Praia: ['Creole / Mestiço', 'African (Badio)'],
      Mindelo: ['Creole / Mestiço', 'Portuguese European'],
      'Santa Maria': ['Creole / Mestiço'],
      Assomada: ['Creole / Mestiço', 'African (Badio)'],
      'São Filipe': ['Creole / Mestiço'],
    },
    ethnicityLanguages: {
      'Creole / Mestiço': ['Cape Verdean Creole', 'Portuguese'],
      'African (Badio)': ['Cape Verdean Creole', 'Portuguese'],
      'Portuguese European': ['Portuguese', 'Cape Verdean Creole'],
      'Mixed / Other': ['Cape Verdean Creole', 'Portuguese'],
    },
    subdivisionLanguages: {
      'Ilhas de Barlavento': ['Cape Verdean Creole', 'Portuguese'],
      'Ilhas de Sotavento': ['Cape Verdean Creole', 'Portuguese'],
    },
  },
  MR: {
    ethnicities: [
      'Beydane (White Moor)',
      'Haratine (Black Moor)',
      'Wolof',
      'Soninke',
      'Fulani',
      'Bambara',
      'Mixed / Other',
    ],
    languages: ['Arabic', 'French', 'Hassaniyya', 'Wolof', 'Soninke', 'Fula'],
    subdivisionEthnicities: {
      'Nouakchott-Nord': ['Beydane (White Moor)', 'Haratine (Black Moor)', 'Wolof'],
      'Nouakchott-Ouest': ['Beydane (White Moor)', 'Haratine (Black Moor)'],
      'Nouakchott-Sud': ['Haratine (Black Moor)', 'Wolof', 'Soninke'],
      Adrar: ['Beydane (White Moor)', 'Haratine (Black Moor)'],
      Assaba: ['Haratine (Black Moor)', 'Soninke'],
      Brakna: ['Haratine (Black Moor)', 'Fulani', 'Soninke'],
      Gorgol: ['Haratine (Black Moor)', 'Fulani', 'Soninke'],
      Guidimaka: ['Soninke', 'Haratine (Black Moor)'],
      Hodh_ech_Chargui: ['Haratine (Black Moor)', 'Beydane (White Moor)'],
      Hodh_el_Gharbi: ['Haratine (Black Moor)', 'Beydane (White Moor)'],
      Inchiri: ['Beydane (White Moor)', 'Haratine (Black Moor)'],
      'Nouadhibou (Dakhlet Nouadhibou)': [
        'Beydane (White Moor)',
        'Haratine (Black Moor)',
        'Wolof',
      ],
      Tagant: ['Beydane (White Moor)', 'Haratine (Black Moor)'],
      'Tiris Zemmour': ['Beydane (White Moor)', 'Haratine (Black Moor)'],
      Trarza: ['Beydane (White Moor)', 'Haratine (Black Moor)', 'Wolof'],
    },
    cityEthnicities: {
      Nouakchott: ['Beydane (White Moor)', 'Haratine (Black Moor)', 'Wolof'],
      Nouadhibou: ['Beydane (White Moor)', 'Haratine (Black Moor)', 'Wolof'],
      Kiffa: ['Haratine (Black Moor)', 'Soninke'],
      Rosso: ['Beydane (White Moor)', 'Haratine (Black Moor)', 'Wolof'],
      Zouérat: ['Beydane (White Moor)', 'Haratine (Black Moor)'],
      Atar: ['Beydane (White Moor)', 'Haratine (Black Moor)'],
      Kaédi: ['Haratine (Black Moor)', 'Fulani', 'Soninke'],
      Sélibabi: ['Soninke', 'Haratine (Black Moor)'],
    },
    ethnicityLanguages: {
      'Beydane (White Moor)': ['Hassaniyya', 'Arabic', 'French'],
      'Haratine (Black Moor)': ['Hassaniyya', 'Arabic', 'French'],
      Wolof: ['Wolof', 'Hassaniyya', 'French'],
      Soninke: ['Soninke', 'Hassaniyya', 'French'],
      Fulani: ['Fula', 'Hassaniyya', 'French'],
      Bambara: ['Bambara', 'Hassaniyya', 'French'],
      'Mixed / Other': ['Hassaniyya', 'Arabic', 'French'],
    },
    subdivisionLanguages: {
      'Nouakchott-Nord': ['Arabic', 'Hassaniyya', 'French'],
      'Nouakchott-Sud': ['Arabic', 'Hassaniyya', 'French'],
      Guidimaka: ['Soninke', 'Arabic', 'French'],
      Gorgol: ['Fula', 'Arabic', 'French'],
    },
  },
  ST: {
    ethnicities: ['Mestiço', 'Forro', 'Angolar', 'Principense', 'Cape Verdean', 'Portuguese European', 'Mixed / Other'],
    languages: ['Portuguese', 'Forro', 'Angolar', 'Principense'],
    subdivisionEthnicities: {
      'São Tomé Island': ['Forro', 'Mestiço', 'Angolar', 'Cape Verdean'],
      'Príncipe Island': ['Principense', 'Mestiço'],
    },
    cityEthnicities: {
      'São Tomé': ['Forro', 'Mestiço', 'Cape Verdean'],
      'Santo António': ['Principense', 'Mestiço'],
    },
    ethnicityLanguages: {
      Mestiço: ['Portuguese', 'Forro'],
      Forro: ['Forro', 'Portuguese'],
      Angolar: ['Angolar', 'Portuguese', 'Forro'],
      Principense: ['Principense', 'Portuguese'],
      'Cape Verdean': ['Portuguese', 'Forro'],
      'Portuguese European': ['Portuguese'],
      'Mixed / Other': ['Portuguese', 'Forro'],
    },
    subdivisionLanguages: {
      'São Tomé Island': ['Portuguese', 'Forro'],
      'Príncipe Island': ['Portuguese', 'Principense'],
    },
  },
  CM: {
    ethnicities: ['Fang', 'Bamileke', 'Bamoun', 'Douala', 'Fulani', 'Bassa', 'Pygmy (Baka)', 'Kirdi', 'Ewondo', 'Ghomala', 'Kom', 'Maka', 'Mixed / Other'],
    languages: ['French', 'English', 'Bulu', 'Fula', 'Ewondo', 'Yemba', 'Ghomala', 'Ngiemboon', 'Kom', 'Basaa', 'Bamun', 'Medumba', 'Mundang'],
    subdivisionEthnicities: {
      Adamawa: ['Fulani', 'Maka'],
      Centre: ['Ewondo', 'Fang', 'Bamileke'],
      East: ['Maka', 'Pygmy (Baka)'],
      'Far North': ['Fulani', 'Kirdi'],
      Littoral: ['Douala', 'Bassa', 'Bamileke'],
      North: ['Fulani', 'Kirdi'],
      Northwest: ['Kom', 'Bamileke'],
      West: ['Bamileke', 'Bamoun'],
      South: ['Fang', 'Pygmy (Baka)'],
      Southwest: ['Bakweri', 'Bamileke'],
    },
    cityEthnicities: {
      Yaoundé: ['Ewondo', 'Fang', 'Bamileke'],
      Douala: ['Douala', 'Bassa', 'Bamileke'],
      Bamenda: ['Kom', 'Bamileke'],
      Garoua: ['Fulani', 'Kirdi'],
      Maroua: ['Fulani', 'Kirdi'],
      Bafoussam: ['Bamileke'],
      Ngaoundéré: ['Fulani', 'Maka'],
      Foumban: ['Bamoun', 'Bamileke'],
      Limbe: ['Bakweri', 'Bamileke'],
      Kumba: ['Bamileke', 'Bassa'],
    },
    ethnicityLanguages: {
      Fang: ['Bulu', 'French'],
      Bamileke: ['Yemba', 'Ghomala', 'Medumba', 'French', 'English'],
      Bamoun: ['Bamun', 'French'],
      Douala: ['Douala', 'French', 'English'],
      Fulani: ['Fula', 'French'],
      Bassa: ['Basaa', 'French'],
      'Pygmy (Baka)': ['Baka', 'French'],
      Kirdi: ['Mundang', 'Fula', 'French'],
      Ewondo: ['Ewondo', 'French'],
      Ghomala: ['Ghomala', 'French'],
      Kom: ['Kom', 'English', 'French'],
      Maka: ['Maka', 'French'],
      'Mixed / Other': ['French', 'English'],
    },
    subdivisionLanguages: {
      Littoral: ['French', 'Douala', 'Basaa'],
      Centre: ['French', 'Ewondo'],
      Northwest: ['English', 'Kom', 'Yemba'],
      West: ['French', 'Yemba', 'Ghomala'],
      North: ['French', 'Fula'],
      'Far North': ['French', 'Fula', 'Mundang'],
      Southwest: ['English', 'French'],
    },
  },
};

export const WEST_AFRICA_LANGUAGES: Record<string, readonly string[]> = {
  NG: ['English', 'Yoruba', 'Nigerian Pidgin', 'Hausa', 'Igbo', 'Nigerian Fulfulde', 'Tiv', 'Efik', 'Ibibio'],
  GH: ['Akan', 'English', 'Ewe', 'Ga', 'Abron', 'Frafra', 'Adangme', 'Nzima'],
  SN: ['Wolof', 'French', 'Fula', 'Serer', 'Jola-Fonyi', 'Saafi-Saafi', 'Mandjak', 'Balanta-Ganja', 'Noon', 'Mankanya', 'Bassari', 'Hassaniyya', 'Ménik'],
  CI: ['French', 'Baoulé', 'Cebaara Senoufo', 'Dan'],
  SL: ['English', 'Krio', 'Mende', 'Timne'],
  LR: ['English', 'Liberian English', 'Kpelle', 'Bassa', 'Kru', 'Grebo', 'Dan', 'Mano', 'Southern Kisi', 'Vai', 'Bandi', 'Mende'],
  GN: ['French', 'Fula', 'Mandingo', 'Susu', "N'Ko", 'Kpelle'],
  ML: ['French', 'Bambara', 'Maasina Fulfulde', 'Soninke', 'Kita Maninkakan', 'Koyraboro Senni', 'Tamashek', 'Koyra Chiini', 'Tomo Kan Dogon', 'Xaasongaxango'],
  BF: ['French', 'Mossi', 'Dyula'],
  GW: ['Portuguese', 'French', 'Mankanya'],
  GM: ['English', 'Mandingo'],
  CV: ['Portuguese', 'Kabuverdianu'],
  TG: ['French', 'Ewe', 'Ifè'],
  BJ: ['French', 'Fon', 'Yoruba'],
  NE: ['French', 'Hausa', 'Zarma', 'Central-Eastern Niger Fulfulde', 'Tamashek'],
  MR: ['Arabic', 'Hassaniyya', 'French', 'Fula'],
  ST: ['Portuguese', 'French'],
  CM: ['French', 'English', 'Bulu', 'Fula', 'Ewondo', 'Yemba', 'Ghomala', 'Ngiemboon', 'Kom', 'Basaa', 'Bamun', 'Medumba', 'Mundang'],
};