import { CountryCultureData } from './types';

export const WEST_AFRICA_CULTURE: Record<string, CountryCultureData> = {
  NG: {
    ethnicities: ['Yoruba', 'Igbo', 'Hausa', 'Fulani', 'Tiv', 'Kanuri', 'Ijaw', 'Edo', 'Efik', 'Ibibio', 'Nupe', 'Urhobo'],
    languages: ['English', 'Yoruba', 'Igbo', 'Hausa', 'Fulfulde', 'Pidgin', 'Kanuri', 'Tiv', 'Edo', 'Ibibio'],
    subdivisionEthnicities: {
      Lagos: ['Yoruba'],
      Oyo: ['Yoruba'],
      Ogun: ['Yoruba'],
      Osun: ['Yoruba'],
      Ondo: ['Yoruba'],
      Anambra: ['Igbo'],
      Imo: ['Igbo'],
      Enugu: ['Igbo'],
      Abia: ['Igbo'],
      Kano: ['Hausa', 'Fulani'],
      Kaduna: ['Hausa', 'Fulani'],
      Sokoto: ['Hausa', 'Fulani'],
      Rivers: ['Ijaw', 'Ikwerre'],
    },
    cityEthnicities: {
      Lagos: ['Yoruba'],
      Ibadan: ['Yoruba'],
      Awka: ['Igbo'],
      Onitsha: ['Igbo'],
      Enugu: ['Igbo'],
      Kano: ['Hausa', 'Fulani'],
      Kaduna: ['Hausa', 'Fulani'],
      'Port Harcourt': ['Ijaw', 'Ikwerre'],
    },
    ethnicityLanguages: {
      Yoruba: ['Yoruba', 'English'],
      Igbo: ['Igbo', 'English'],
      Hausa: ['Hausa', 'English'],
      Fulani: ['Fulfulde', 'Hausa', 'English'],
      Tiv: ['Tiv', 'English'],
      Kanuri: ['Kanuri', 'English'],
      Ijaw: ['English', 'Pidgin'],
      Edo: ['Edo', 'English'],
      Efik: ['Efik', 'English'],
      Ibibio: ['Ibibio', 'English'],
      Nupe: ['Nupe', 'English'],
      Urhobo: ['Urhobo', 'English'],
    },
  },
  GH: {
    ethnicities: ['Akan', 'Ewe', 'Ga', 'Dagomba', 'Gurma', 'Guan', 'Fante', 'Ashanti'],
    languages: ['English', 'Twi', 'Ga', 'Ewe', 'Fante', 'Dagbani'],
    subdivisionEthnicities: {
      'Greater Accra': ['Ga', 'Akan', 'Ewe'],
      Ashanti: ['Ashanti', 'Akan'],
      Central: ['Fante', 'Akan'],
      Volta: ['Ewe'],
      Northern: ['Dagomba'],
    },
    ethnicityLanguages: {
      Akan: ['Twi', 'English'],
      Ewe: ['Ewe', 'English'],
      Ga: ['Ga', 'English'],
      Dagomba: ['Dagbani', 'English'],
      Gurma: ['English'],
      Guan: ['English'],
      Fante: ['Fante', 'English'],
      Ashanti: ['Twi', 'English'],
    },
  },
};
