export default {
  "28": [
    "Chagni",
    "Shendi"
  ],
  "Somali": [
    "Arabi",
    "Chinahsen",
    "Degeh Bur",
    "Digih Habar Es",
    "El Bahay",
    "Fadhigaradle",
    "Gedeb",
    "Gode",
    "Golwayn",
    "Hartishek",
    "Jijiga",
    "Kahandhale",
    "Kebri Dahar",
    "Lasoano",
    "Neefkuceliye",
    "Qorof",
    "Raqo",
    "Waal",
    "Warder",
    "Yamarugley"
  ],
  "Oromiya": [
    "'Alem T'ena",
    "'Alemaya",
    "Adis 'Alem",
    "Agaro",
    "Ara Ali",
    "Arsi Negele",
    "Asasa",
    "Asbe Teferi",
    "Asela",
    "Ayana",
    "Babile",
    "Bale Robe",
    "Bedele",
    "Bedesa",
    "Bek'oji",
    "Bishoftu",
    "Burayu",
    "Chelenko",
    "Daye",
    "Deder",
    "Dembi Dolo",
    "Dera",
    "Dodola",
    "Felana",
    "Fiche",
    "Funyan Bira",
    "Gebre Guracha",
    "Gedo",
    "Gelemso",
    "Genet",
    "Ghinnir",
    "Gimbi",
    "Ginch'i",
    "Goba",
    "Gobesa",
    "Guder",
    "Gutin",
    "Hagere Hiywet",
    "Hagere Maryam",
    "Hirna",
    "Huruta",
    "Iteya",
    "Jimma",
    "Kachisi",
    "Kele",
    "Kercha",
    "Kibre Mengist",
    "Kofele",
    "Kuyera",
    "Mek'i",
    "Mena",
    "Mendi",
    "Metahara",
    "Metu",
    "Mi'eso",
    "Mojo",
    "Nazret",
    "Negele",
    "Nejo",
    "Nek'emte",
    "Sagure",
    "Sebeta",
    "Sendafa",
    "Shakiso",
    "Shambu",
    "Shashamane",
    "Sheno",
    "Sire",
    "Suntu",
    "Tulu Bolo",
    "Waliso",
    "Welench'iti",
    "Wenji",
    "Wonji",
    "Yabelo",
    "Ziway"
  ],
  "South Ethiopia Regional State": [
    "Arba Minch",
    "Areka",
    "Badessa",
    "Bako",
    "Bale Hawassa",
    "Bedesa",
    "Boditi",
    "Ch'ench'a",
    "Dila",
    "Dimtu",
    "Felege Neway",
    "Gasuba",
    "Gidole",
    "Gununo",
    "Jinka",
    "Shanto",
    "Sodo",
    "Tebela",
    "Wenago",
    "Yirga Ch'efe"
  ],
  "Sidama Region": [
    "Awasa",
    "Ch'iko",
    "Leku",
    "Wendo",
    "Yirga 'Alem"
  ],
  "Tigray": [
    "Abala",
    "Abiy Adi",
    "Adebaye",
    "Adigrat",
    "Adwa",
    "Aksum",
    "Alamata",
    "Dolo",
    "Idaga Hamus",
    "Inda Silase",
    "Indabaguna",
    "Intich'o",
    "Korem",
    "May Cadera",
    "Maych'ew",
    "Mek'ele",
    "Sheraro",
    "Wik'ro"
  ],
  "Amhara": [
    "'Alem Ketema",
    "Abderafi",
    "Abomsa",
    "Adet",
    "Adis K'idame",
    "Adis Zemen",
    "Amba Giorgis",
    "At'aye",
    "Aykel",
    "Bahir Dar",
    "Bati",
    "Bichena",
    "Bure",
    "Dabat",
    "Dangila",
    "Debark'",
    "Debre Birhan",
    "Debre Mark'os",
    "Debre Tabor",
    "Dembech'a",
    "Dessie",
    "Filakit",
    "Finote Selam",
    "Gimja Bet Maryam",
    "Ginja Bet",
    "Gonder",
    "Gurbete",
    "Harbu",
    "Hayk'",
    "Ibnat",
    "Injibara",
    "K'ola Diba",
    "Kemise",
    "Kobo",
    "Kombolcha",
    "Lalibela",
    "Lumame",
    "Maksenyit",
    "Mehal Meda",
    "Mer'awi",
    "Mersa",
    "Mertule Maryam",
    "Metemma",
    "Mot'a",
    "Nefas Mewch'a",
    "Robit",
    "Sek'ot'a",
    "T'is Isat",
    "Tikil Dingay",
    "Tilili",
    "Wegeda",
    "Weldiya",
    "Were Ilu",
    "Werota"
  ],
  "Central Ethiopia Regional State": [
    "Butajira",
    "Ciro",
    "Damboya",
    "Durame",
    "Gimbicho",
    "Hadero",
    "Hosa'ina",
    "Inseno",
    "K'olito",
    "Shinshicho",
    "Shone",
    "Welk'it'e",
    "Worabe"
  ],
  "South West Ethiopia Peoples' Region": [
    "Bonga",
    "Komtikas",
    "Mizan Teferi",
    "Tarch'a Sodo",
    "Tepi",
    "Wacha",
    "Waka"
  ],
  "Āfar": [
    "Arerti",
    "Asaita",
    "Awash",
    "Dubti",
    "Logiya",
    "Mehoni",
    "Mile",
    "Samara",
    "Sifra"
  ],
  "Bīnshangul Gumuz": [
    "Asosa",
    "Bambesi",
    "Dibate",
    "Mambuk"
  ],
  "Harari": [
    "Harar"
  ],
  "Gambela": [
    "Gambela"
  ],
  "Dire Dawa": [
    "Dire Dawa"
  ],
  "Addis Ababa": [
    "Addis Ababa"
  ]
} as const;
