export default {
  "Laâyoune-Sakia El Hamra": [
    "Smara"
  ],
  "Marrakesh-Safi": [
    "Ait Ourir",
    "Amizmiz",
    "Asni",
    "Ben Guerir",
    "Chichaoua",
    "Echemmaia Est",
    "El Kelaa des Srarhna",
    "Essaouira",
    "Imi-n-Tanout",
    "Laattaouia",
    "Marrakesh",
    "Mechouar-Kasba",
    "Safi",
    "Sebt Gzoula",
    "Setti Fatma",
    "Tamallalt",
    "Tamansourt",
    "Youssoufia"
  ],
  "Béni Mellal-Khénifra": [
    "Aguelmous",
    "Al Fqih Ben Calah",
    "Azilal",
    "Bejaad",
    "Beni Mellal",
    "Boujniba",
    "Boumia",
    "Demnate",
    "El Ksiba",
    "Kasba Tadla",
    "Khenifra",
    "Khouribga",
    "Midelt",
    "Mrirt",
    "Oued Zem",
    "Oulad Ayad",
    "Souq Sebt Oulad Nemma",
    "Zawyat ech Cheikh"
  ],
  "Oriental": [
    "Ahfir",
    "Ain Beni Mathar",
    "Al Aaroui",
    "Ben Taieb",
    "Beni Enzar",
    "Berkane",
    "Bouarfa",
    "Driouch",
    "El Aioun",
    "Jerada",
    "Midar",
    "Nador",
    "Oujda",
    "Selouane",
    "Sidi Slimane Echcharaa",
    "Taourirt",
    "Zaio",
    "Zeghanghane"
  ],
  "Drâa-Tafilalet": [
    "Arfoud",
    "Errachidia",
    "Goulmima",
    "Kelaat Mgouna",
    "Moulay Ali Cherif",
    "Ouarzazate",
    "Recani",
    "Rich",
    "Tabount",
    "Tinghir",
    "Zagora"
  ],
  "Souss-Massa": [
    "Agadir",
    "Ait Melloul",
    "Ait Yazza",
    "Aoulouz",
    "Aourir",
    "Ben Jerrar",
    "Dakhla",
    "Dchira El Jihadia",
    "Inezgane",
    "Lqoliaa",
    "My Drarga",
    "Oadar Temsia",
    "Oulad Barhil",
    "Oulad Teima",
    "Sidi Ifni",
    "Taroudant",
    "Tata",
    "Tine Biougra",
    "Tiznit"
  ],
  "Casablanca-Settat": [
    "Ad Darwa",
    "Ain Harrouda",
    "Al Brouj",
    "Azemmour",
    "Ben Ahmed",
    "Beni Yakhlef",
    "Benslimane",
    "Berrechid",
    "Bir Jdid",
    "Bouskoura",
    "Bouznika",
    "Casablanca",
    "Dar Bouazza",
    "El Gara",
    "El Jadida",
    "El Mansouria",
    "Had Soualem",
    "Lahraouyine",
    "Mediouna",
    "Mohammedia",
    "Settat",
    "Sidi Bennour",
    "Sidi Rahal",
    "Tit Mellil",
    "Zawyat an Nwacer"
  ],
  "Tanger-Tetouan-Al Hoceima": [
    "Al Hoceima",
    "Asilah",
    "Bni Bouayach",
    "Chefchaouen",
    "Fnidek",
    "Gueznaia",
    "Imzouren",
    "Ksar El Kebir",
    "Larache",
    "Martil",
    "Mdiq",
    "Ouezzane",
    "Tangier",
    "Tetouan",
    "Tirhanimine"
  ],
  "Rabat-Salé-Kénitra": [
    "Ain Attig",
    "Ain El Aouda",
    "Bouknadel",
    "El Harhoura",
    "Kenitra",
    "Khemisset",
    "Lalla Mimouna",
    "Mechraa Bel Ksiri",
    "Mehdya",
    "Mers El Kheir",
    "Oulmes",
    "Rabat",
    "Sale",
    "Sale Al Jadida",
    "Sidi Allal El Bahraoui",
    "Sidi Kacem",
    "Sidi Slimane",
    "Sidi Taibi",
    "Sidi Yahia El Gharb",
    "Skhirate",
    "Souk El Arbaa",
    "Souk et Tnine Jorf el Mellah",
    "Souq Larb'a al Gharb",
    "Tamesna",
    "Temara",
    "Tiflet"
  ],
  "Fès-Meknès": [
    "Agourai",
    "Ain Taoujdat",
    "Azrou",
    "Douar Toulal",
    "El Hajeb",
    "Fes",
    "Fes al Bali",
    "Guercif",
    "Ifrane",
    "Imouzzer Kandar",
    "Karia Ba Mohamed",
    "Meknes",
    "Missour",
    "New Fes",
    "Ouislane",
    "Oulad Tayeb",
    "Outat Oulad Al Haj",
    "Ras el Ma",
    "Ribat Al Khayr",
    "Sabaa Aiyoun",
    "Sefrou",
    "Tahla",
    "Taounate",
    "Taza"
  ],
  "Guelmim-Oued Noun": [
    "Assa",
    "Bou Izakarn",
    "Guelmim",
    "Tan-Tan"
  ]
} as const;
