export default {
  "Gauteng": [
    "Alberton",
    "Alexandra",
    "Bagale",
    "Benoni",
    "Boksburg",
    "Brakpan",
    "Bronkhorstspruit",
    "Carletonville",
    "Centurion",
    "Cullinan",
    "Diepsloot",
    "Edenvale",
    "Ekangala",
    "Etwatwa",
    "Evaton",
    "Germiston",
    "Heidelberg",
    "Ivory Park",
    "Johannesburg",
    "Krugersdorp",
    "Mabopane",
    "Midrand",
    "Midstream",
    "Nigel",
    "Pretoria",
    "Randburg",
    "Randfontein",
    "Roodepoort",
    "Soshanguve",
    "Soweto",
    "Springs",
    "Thembisa",
    "Tokoza",
    "Vanderbijlpark",
    "Vereeniging",
    "Verena",
    "Westonaria"
  ],
  "North West": [
    "Bloemhof",
    "Brits",
    "Christiana",
    "Coligny",
    "Fochville",
    "Ga-Rankuwa",
    "Hammanskraal",
    "Hartbeesfontein",
    "Hartbeespoort",
    "Hartbeestfontein-A",
    "Itsoseng",
    "Klerksdorp",
    "Koster",
    "Leeudoringstad",
    "Letlhabile",
    "Lichtenburg",
    "Mafikeng",
    "Makwassie",
    "Marikana",
    "Mmabatho",
    "Orkney",
    "Ottosdal",
    "Potchefstroom",
    "Rustenburg",
    "Schweizer-Reneke",
    "Stilfontein",
    "Ventersdorp",
    "Vryburg",
    "Wolmaransstad",
    "Zeerust"
  ],
  "Free State": [
    "Allanridge",
    "Bethlehem",
    "Bloemfontein",
    "Bothaville",
    "Botshabelo",
    "Bultfontein",
    "Deneysville",
    "Ficksburg",
    "Fouriesburg",
    "Frankfort",
    "Harrismith",
    "Heilbron",
    "Hennenman",
    "Hlohlolwane",
    "Hoopstad",
    "Koppies",
    "Kroonstad",
    "Kutloanong",
    "Ladybrand",
    "Mamafubedu",
    "Marquard",
    "Odendaalsrus",
    "Parys",
    "Phomolong",
    "Phuthaditjhaba",
    "Reitz",
    "Sasolburg",
    "Senekal",
    "Thaba Nchu",
    "Theunissen",
    "Tshiame",
    "Viljoenskroon",
    "Villiers",
    "Virginia",
    "Vrede",
    "Vredefort",
    "Welkom",
    "Wesselsbron",
    "Winburg",
    "Winnie Mandela",
    "Zastron"
  ],
  "Mpumalanga": [
    "Balfour",
    "Barberton",
    "Belfast",
    "Bethal",
    "Breyten",
    "Calcutta",
    "Carolina",
    "Daggakraal",
    "Delmas",
    "Driefontein",
    "Driekoppies",
    "Emalahleni",
    "eMbalenhle",
    "Empuluzu",
    "Ermelo",
    "Fernie",
    "Hendrina",
    "Hlanganani",
    "Kamaqhekeza",
    "Kinross",
    "Komatipoort",
    "Kriel",
    "Kwaggafontein",
    "Lebohang",
    "Leslie",
    "Lukwatini",
    "Lydenburg",
    "Mafemani",
    "Matsulu",
    "Mbombela",
    "Middelburg",
    "Mkhuhlu",
    "Moloto South",
    "Nhlazatje",
    "Phola",
    "Piet Retief",
    "Redhill",
    "Sabie",
    "Schoemansdal",
    "Secunda",
    "Siyabuswa",
    "Somaroboro",
    "Standerton",
    "Tekwane",
    "Thubelihle",
    "Trichardt",
    "Vaalbank",
    "Volksrust",
    "White River"
  ],
  "Eastern Cape": [
    "Alice",
    "Aliwal North",
    "Bhisho",
    "Burgersdorp",
    "Butterworth",
    "Cala",
    "Clydesdale",
    "Cradock",
    "Dimbaza",
    "East London",
    "Fort Beaufort",
    "Gonubie",
    "Gqeberha",
    "Graaff Reinet",
    "Grahamstown",
    "Humansdorp",
    "Jeffreys Bay",
    "Kariega",
    "Khowa",
    "Kruisfontein",
    "Lady Frere",
    "Mdantsane",
    "Middelburg",
    "Mthatha",
    "Ndevana",
    "Port Alfred",
    "Qonce",
    "Queensdale",
    "Queenstown",
    "Somerset East",
    "Stutterheim",
    "Tlokoeng",
    "Ugie",
    "Whittlesea"
  ],
  "KwaZulu-Natal": [
    "Ballitoville",
    "Dundee",
    "Durban",
    "eMkhomazi",
    "Empangeni",
    "eMuziwezinto",
    "Eshowe",
    "eSikhaleni",
    "Estcourt",
    "Folweni",
    "Frischgewaagd",
    "Ga-Malakhe",
    "Glencoe",
    "Greytown",
    "Howick",
    "Kokstad",
    "KwaDukuza",
    "Ladysmith",
    "Mandeni",
    "Margate",
    "Mondlo",
    "Mooi River",
    "Mpophomeni",
    "Mpumalanga",
    "Mtubatuba",
    "Ncotshane",
    "Newcastle",
    "Ntuzuma",
    "Pietermaritzburg",
    "Pinetown",
    "Port Shepstone",
    "Richards Bay",
    "Richmond",
    "Scottburgh",
    "Shakaskraal",
    "Tongaat",
    "Ulundi",
    "Vryheid",
    "Wembesi"
  ],
  "Northern Cape": [
    "De Aar",
    "Kimberley",
    "Pampierstad",
    "Postmasburg",
    "Upington",
    "Warrenton"
  ],
  "Limpopo": [
    "Acornhoek",
    "Amandelbult",
    "Bela Bela",
    "Duiwelskloof",
    "Dwarsloop",
    "Giyani",
    "Lebowakgomo",
    "Lephalale",
    "Louis Trichardt",
    "Malamulele",
    "Mankweng",
    "Marapong",
    "Modimolle",
    "Mokopane",
    "Mookgophong",
    "Musina",
    "Nkowakowa",
    "Northam",
    "Phalaborwa",
    "Polokwane",
    "Praktiseer",
    "Thabazimbi",
    "Thohoyandou",
    "Thulamahashi",
    "Tshitereke",
    "Tzaneen",
    "Vaalwater"
  ],
  "Western Cape": [
    "Ashton",
    "Athlone",
    "Atlantis",
    "Beaufort West",
    "Bredasdorp",
    "Caledon",
    "Cape Town",
    "Ceres",
    "Durbanville",
    "Dysselsdorp",
    "Franschhoek",
    "Gansbaai",
    "George",
    "Grabouw",
    "Groot-Brakrivier",
    "Hermanus",
    "Knysna",
    "Kraaifontein",
    "Kuils River",
    "Lansdowne",
    "Le Roux",
    "Malmesbury",
    "Montagu",
    "Moorreesburg",
    "Mossel Bay",
    "Muizenberg",
    "Oudtshoorn",
    "Paarl",
    "Plettenberg Bay",
    "Retreat",
    "Riversdale",
    "Robertson",
    "Rondebosch",
    "Saldanha",
    "Somerset West",
    "Stellenbosch",
    "Swellendam",
    "Vredenburg",
    "Vredendal",
    "Wellington",
    "Worcester"
  ]
} as const;
