export default {
  "Sassandra-Marahoué": [
    "Aboka",
    "Ancien-Prozi",
    "Baoutifla",
    "Bediala",
    "Belleville",
    "Boboniessoko",
    "Bognonzra",
    "Bonon",
    "Bonoufla",
    "Bouafle",
    "Daloa",
    "Gadouan",
    "Gonate",
    "Guessabo",
    "Issia",
    "Konefla",
    "Luenoufla",
    "Mignoure",
    "Pelezi",
    "Saioua",
    "Vavoua",
    "Vrouo",
    "Zaibo",
    "Zaliohouan",
    "Zoukougbeu",
    "Zuenoula"
  ],
  "Montagnes": [
    "Bahe-Blaon",
    "Baibli",
    "Bangolo",
    "Bangolo Tahouake",
    "Biankouma",
    "Blenimeouin",
    "Blolequin",
    "Danane",
    "Diehiba",
    "Diourouzon",
    "Duekoue",
    "Fengolo",
    "Gbapleu",
    "Gohouo",
    "Goya",
    "Guezon",
    "Guiglo",
    "Kahin",
    "Kouibly",
    "Kranzadougou",
    "Logouale",
    "Mahapleu",
    "Man",
    "Nizahon II",
    "Zagne",
    "Zeaglo",
    "Zou",
    "Zouan-Hounien"
  ],
  "Lacs District": [
    "Daoukro",
    "Dimbokro",
    "M'Bahiakro",
    "Tiebissou",
    "Toumodi",
    "Yamoussoukro"
  ],
  "Bas-Sassandra District": [
    "Balakouya",
    "Belleville",
    "Buyo",
    "Dagadji",
    "Dagbao I",
    "Djapadji",
    "Gabiadji",
    "Gagny",
    "Gaoulou",
    "Gbabam",
    "Gligbeuadji",
    "Gnago",
    "Gnepasso",
    "Grand-Zattry",
    "Gueyo",
    "Lobakuya",
    "Loboville",
    "Mabehiri",
    "Meagui",
    "Niapidou",
    "Okromodou",
    "Okrouyo",
    "Oupoyo",
    "Para",
    "Petit Grabo",
    "Petitgoa I",
    "Sahoua",
    "San-Pedro",
    "Sassandra",
    "Soubre",
    "Tabou",
    "Touagui",
    "Touih",
    "Watte",
    "Yabayo"
  ],
  "Woroba": [
    "Borotou-Koro",
    "Dianra",
    "Mankono",
    "Seguela",
    "Touba"
  ],
  "Vallée du Bandama District": [
    "Beoumi",
    "Bouake",
    "Dabakala",
    "Fronan",
    "Katiola",
    "Niakaramandougou",
    "Sakassou",
    "Tafire",
    "Tortiya"
  ],
  "Savanes District": [
    "Boundiali",
    "Diawala",
    "Dikodougou",
    "Ferkessedougou",
    "Kaouara",
    "Kolia",
    "Kong",
    "Korhogo",
    "M'Bengue",
    "Nambingue",
    "Nielle",
    "Ouangolodougou",
    "Tengrela"
  ],
  "Lagunes District": [
    "Adzope",
    "Affery",
    "Agboville",
    "Ahouanou",
    "Akoupe",
    "Azaguie",
    "Becedi-Brignan",
    "Bieby",
    "Dabou",
    "Gbolouville",
    "Grand-Lahou",
    "Ndouci",
    "Nzianouan",
    "Rubino",
    "Tiassale"
  ],
  "Zanzan District": [
    "Bondoukou",
    "Bouna",
    "Doropo",
    "Flakiedougou",
    "Sinfra",
    "Tanda"
  ],
  "Gôh-Djiboua": [
    "Bayota",
    "Diegonefla",
    "Dignago",
    "Divo",
    "Doukouya",
    "Eremankono",
    "Gagnoa",
    "Galebre",
    "Gnatroa",
    "Guepaouo",
    "Guiberoua",
    "Hire",
    "Lakota",
    "Moussadougou",
    "Ogoudou",
    "Oume"
  ],
  "Denguélé District": [
    "Odienne"
  ],
  "Comoé District": [
    "Abengourou",
    "Aboisso",
    "Aboisso Comoe",
    "Adiake",
    "Agnibilekrou",
    "Ahigbe Koffikro",
    "Ande",
    "Arrah",
    "Bianouan",
    "Bongouanou",
    "Bonoua",
    "Ebilassokro",
    "Grand-Bassam",
    "M'Batto",
    "Mafere",
    "Niable"
  ],
  "Abidjan Autonomous District": [
    "Abidjan",
    "Abobo",
    "Anyama",
    "Bingerville",
    "Koumassi",
    "Marcory"
  ]
} as const;
